// Subject headings from backend/data/math/msc_master_source.csv (MSC).
window.MSC_SUBJECTS = {
  "00": "General and overarching topics; collections",
  "00A": "General and miscellaneous specific topics",
  "00B": "Conference proceedings and collections of articles",
  "01": "History and biography",
  "01A": "History of mathematics and mathematicians",
  "03": "Mathematical logic and foundations",
  "03A": "Philosophical aspects of logic and foundations",
  "03B": "General logic",
  "03C": "Model theory",
  "03D": "Computability and recursion theory",
  "03E": "Set theory",
  "03F": "Proof theory and constructive mathematics",
  "03G": "Algebraic logic",
  "03H": "Nonstandard models",
  "05": "Combinatorics",
  "05A": "Enumerative combinatorics",
  "05B": "Designs and configurations",
  "05C": "Graph theory",
  "05D": "Extremal combinatorics",
  "05E": "Algebraic combinatorics",
  "06": "Order, lattices, ordered algebraic structures",
  "06A": "Ordered sets",
  "06B": "Lattices",
  "06C": "Modular lattices, complemented lattices",
  "06D": "Distributive lattices",
  "06E": "Boolean algebras (Boolean rings)",
  "06F": "Ordered structures",
  "08": "General algebraic systems",
  "08A": "Algebraic structures",
  "08B": "Varieties",
  "08C": "Other classes of algebras",
  "11": "Number theory",
  "11A": "Elementary number theory",
  "11B": "Sequences and sets",
  "11C": "Polynomials and matrices",
  "11D": "Diophantine equations",
  "11E": "Forms and linear algebraic groups",
  "11F": "Discontinuous groups and automorphic forms",
  "11G": "Arithmetic algebraic geometry (Diophantine geometry)",
  "11H": "Geometry of numbers",
  "11J": "Diophantine approximation, transcendental number theory",
  "11K": "Probabilistic theory: distribution modulo \\(1\\); metric theory of algorithms",
  "11L": "Exponential sums and character sums",
  "11M": "Zeta and \\(L\\)-functions: analytic theory",
  "11N": "Multiplicative number theory",
  "11P": "Additive number theory; partitions",
  "11R": "Algebraic number theory: global fields",
  "11S": "Algebraic number theory: local fields",
  "11T": "Finite fields and commutative rings (number-theoretic aspects)",
  "11U": "Connections of number theory and logic",
  "11Y": "Computational number theory",
  "11Z": "Miscellaneous applications of number theory",
  "12": "Field theory and polynomials",
  "12D": "Real and complex fields",
  "12E": "General field theory",
  "12F": "Field extensions",
  "12G": "Homological methods (field theory)",
  "12H": "Differential and difference algebra",
  "12J": "Topological fields",
  "12K": "Generalizations of fields",
  "12L": "Connections between field theory and logic",
  "13": "Commutative algebra",
  "13A": "General commutative ring theory",
  "13B": "Commutative ring extensions and related topics",
  "13C": "Theory of modules and ideals in commutative rings",
  "13D": "Homological methods in commutative ring theory",
  "13E": "Chain conditions, finiteness conditions in commutative ring theory",
  "13F": "Arithmetic rings and other special commutative rings",
  "13G": "Integral domains",
  "13H": "Local rings and semilocal rings",
  "13J": "Topological rings and modules",
  "13L": "Applications of logic to commutative algebra",
  "13M": "Finite commutative rings",
  "13N": "Differential algebra",
  "13P": "Computational aspects and applications of commutative rings",
  "14": "Algebraic geometry",
  "14A": "Foundations of algebraic geometry",
  "14B": "Local theory in algebraic geometry",
  "14C": "Cycles and subschemes",
  "14D": "Families, fibrations in algebraic geometry",
  "14E": "Birational geometry",
  "14F": "(Co)homology theory in algebraic geometry",
  "14G": "Arithmetic problems in algebraic geometry; Diophantine geometry",
  "14H": "Curves in algebraic geometry",
  "14J": "Surfaces and higher-dimensional varieties",
  "14K": "Abelian varieties and schemes",
  "14L": "Algebraic groups",
  "14M": "Special varieties",
  "14N": "Projective and enumerative algebraic geometry",
  "14P": "Real algebraic and real-analytic geometry",
  "14Q": "Computational aspects in algebraic geometry",
  "14R": "Affine geometry",
  "14T": "Tropical geometry",
  "15": "Linear and multilinear algebra; matrix theory",
  "15A": "Basic linear algebra",
  "15B": "Special matrices",
  "16": "Associative rings and algebras",
  "16B": "General and miscellaneous",
  "16D": "Modules, bimodules and ideals in associative algebras",
  "16E": "Homological methods in associative algebras",
  "16G": "Representation theory of associative rings and algebras",
  "16H": "Associative algebras and orders",
  "16K": "Division rings and semisimple Artin rings",
  "16L": "Local rings and generalizations",
  "16N": "Radicals and radical properties of associative rings",
  "16P": "Chain conditions, growth conditions, and other forms of finiteness for associative rings and algebras",
  "16R": "Rings with polynomial identity",
  "16S": "Associative rings and algebras arising under various constructions",
  "16T": "Hopf algebras, quantum groups and related topics",
  "16U": "Conditions on elements",
  "16W": "Associative rings and algebras with additional structure",
  "16Y": "Generalizations",
  "16Z": "Computational aspects of associative rings",
  "17": "Nonassociative rings and algebras",
  "17A": "General nonassociative rings",
  "17B": "Lie algebras and Lie superalgebras",
  "17C": "Jordan algebras (algebras, triples and pairs)",
  "17D": "Other nonassociative rings and algebras",
  "18": "Category theory; homological algebra",
  "18A": "General theory of categories and functors",
  "18B": "Special categories",
  "18C": "Categories and theories",
  "18D": "Categorical structures",
  "18E": "Categorical algebra",
  "18F": "Categories in geometry and topology",
  "18G": "Homological algebra in category theory, derived categories and functors",
  "18M": "Monoidal categories and operads",
  "18N": "Higher categories and homotopical algebra",
  "19": "\\(K\\)-theory",
  "19A": "Grothendieck groups and \\(K_0\\)",
  "19B": "Whitehead groups and \\(K_1\\)",
  "19C": "Steinberg groups and \\(K_2\\)",
  "19D": "Higher algebraic \\(K\\)-theory",
  "19E": "\\(K\\)-theory in geometry",
  "19F": "\\(K\\)-theory in number theory",
  "19G": "\\(K\\)-theory of forms",
  "19J": "Obstructions from topology",
  "19K": "\\(K\\)-theory and operator algebras",
  "19L": "Topological \\(K\\)-theory",
  "19M": "Miscellaneous applications of \\(K\\)-theory",
  "20": "Group theory and generalizations",
  "20A": "Foundations",
  "20B": "Permutation groups",
  "20C": "Representation theory of groups",
  "20D": "Abstract finite groups",
  "20E": "Structure and classification of infinite or finite groups",
  "20F": "Special aspects of infinite or finite groups",
  "20G": "Linear algebraic groups and related topics",
  "20H": "Other groups of matrices",
  "20J": "Connections of group theory with homological algebra and category theory",
  "20K": "Abelian groups",
  "20L": "Groupoids (i.e. small categories in which all morphisms are isomorphisms)",
  "20M": "Semigroups",
  "20N": "Other generalizations of groups",
  "20P": "Probabilistic methods in group theory",
  "22": "Topological groups, Lie groups",
  "22A": "Topological and differentiable algebraic systems",
  "22B": "Locally compact abelian groups (LCA groups)",
  "22C": "Compact groups",
  "22D": "Locally compact groups and their algebras",
  "22E": "Lie groups",
  "22F": "Noncompact transformation groups",
  "26": "Real functions",
  "26A": "Functions of one variable",
  "26B": "Functions of several variables",
  "26C": "Polynomials, rational functions in real analysis",
  "26D": "Inequalities in real analysis",
  "26E": "Miscellaneous topics in real functions",
  "28": "Measure and integration",
  "28A": "Classical measure theory",
  "28B": "Set functions, measures and integrals with values in abstract spaces",
  "28C": "Set functions and measures on spaces with additional structure",
  "28D": "Measure-theoretic ergodic theory",
  "28E": "Miscellaneous topics in measure theory",
  "30": "Functions of a complex variable",
  "30A": "General properties of functions of one complex variable",
  "30B": "Series expansions of functions of one complex variable",
  "30C": "Geometric function theory",
  "30D": "Entire and meromorphic functions of one complex variable, and related topics",
  "30E": "Miscellaneous topics of analysis in the complex plane",
  "30F": "Riemann surfaces",
  "30G": "Generalized function theory",
  "30H": "Spaces and algebras of analytic functions of one complex variable",
  "30J": "Function theory on the disc",
  "30K": "Universal holomorphic functions of one complex variable",
  "30L": "Analysis on metric spaces",
  "31": "Potential theory",
  "31A": "Two-dimensional potential theory",
  "31B": "Higher-dimensional potential theory",
  "31C": "Generalizations of potential theory",
  "31D": "Axiomatic potential theory",
  "31E": "Potential theory on fractals and metric spaces",
  "32": "Several complex variables and analytic spaces",
  "32A": "Holomorphic functions of several complex variables",
  "32B": "Local analytic geometry",
  "32C": "Analytic spaces",
  "32D": "Analytic continuation",
  "32E": "Holomorphic convexity",
  "32F": "Geometric convexity in several complex variables",
  "32G": "Deformations of analytic structures",
  "32H": "Holomorphic mappings and correspondences",
  "32J": "Compact analytic spaces",
  "32K": "Generalizations of analytic spaces",
  "32L": "Holomorphic fiber spaces",
  "32M": "Complex spaces with a group of automorphisms",
  "32N": "Automorphic functions",
  "32P": "Non-Archimedean analysis",
  "32Q": "Complex manifolds",
  "32S": "Complex singularities",
  "32T": "Pseudoconvex domains",
  "32U": "Pluripotential theory",
  "32V": "CR manifolds",
  "32W": "Differential operators in several variables",
  "33": "Special functions",
  "33B": "Elementary classical functions",
  "33C": "Hypergeometric functions",
  "33D": "Basic hypergeometric functions",
  "33E": "Other special functions",
  "33F": "Computational aspects of special functions",
  "34": "Ordinary differential equations",
  "34A": "General theory for ordinary differential equations",
  "34B": "Boundary value problems for ordinary differential equations",
  "34C": "Qualitative theory for ordinary differential equations",
  "34D": "Stability theory for ordinary differential equations",
  "34E": "Asymptotic theory for ordinary differential equations",
  "34F": "Ordinary differential equations and systems with randomness",
  "34G": "Differential equations in abstract spaces",
  "34H": "Control problems involving ordinary differential equations",
  "34K": "Functional-differential equations (including equations with delayed, advanced or state-dependent argument)",
  "34L": "Ordinary differential operators",
  "34M": "Ordinary differential equations in the complex domain",
  "34N": "Dynamic equations on time scales or measure chains",
  "35": "Partial differential equations",
  "35A": "General topics in partial differential equations",
  "35B": "Qualitative properties of solutions to partial differential equations",
  "35C": "Representations of solutions to partial differential equations",
  "35D": "Generalized solutions to partial differential equations",
  "35E": "Partial differential equations and systems of partial differential equations with constant coefficients",
  "35F": "General first-order partial differential equations and systems of first-order partial differential equations",
  "35G": "General higher-order partial differential equations and systems of higher-order partial differential equations",
  "35H": "Close-to-elliptic equations",
  "35J": "Elliptic equations and elliptic systems",
  "35K": "Parabolic equations and parabolic systems",
  "35L": "Hyperbolic equations and hyperbolic systems",
  "35M": "Partial differential equations of mixed type and mixed-type systems of partial differential equations",
  "35N": "Overdetermined problems for partial differential equations and systems of partial differential equations",
  "35P": "Spectral theory and eigenvalue problems for partial differential equations",
  "35Q": "Partial differential equations of mathematical physics and other areas of application",
  "35R": "Miscellaneous topics in partial differential equations",
  "35S": "Pseudodifferential operators and other generalizations of partial differential operators",
  "37": "Dynamical systems and ergodic theory",
  "37A": "Ergodic theory",
  "37B": "Topological dynamics",
  "37C": "Smooth dynamical systems: general theory",
  "37D": "Dynamical systems with hyperbolic behavior",
  "37E": "Low-dimensional dynamical systems",
  "37F": "Dynamical systems over complex numbers",
  "37G": "Local and nonlocal bifurcation theory for dynamical systems",
  "37H": "Random dynamical systems",
  "37J": "Dynamical aspects of finite-dimensional Hamiltonian and Lagrangian systems",
  "37K": "Dynamical system aspects of infinite-dimensional Hamiltonian and Lagrangian systems",
  "37L": "Infinite-dimensional dissipative dynamical systems",
  "37M": "Approximation methods and numerical treatment of dynamical systems",
  "37N": "Applications of dynamical systems",
  "37P": "Arithmetic and non-Archimedean dynamical systems",
  "39": "Difference and functional equations",
  "39A": "Difference equations",
  "39B": "Functional equations and inequalities",
  "40": "Sequences, series, summability",
  "40A": "Convergence and divergence of infinite limiting processes",
  "40B": "Multiple sequences and series",
  "40C": "General summability methods",
  "40D": "Direct theorems on summability",
  "40E": "Inversion theorems",
  "40F": "Absolute and strong summability",
  "40G": "Special methods of summability",
  "40H": "Functional analytic methods in summability",
  "40J": "Summability in abstract structures",
  "41": "Approximations and expansions",
  "41A": "Approximations and expansions",
  "42": "Harmonic analysis on Euclidean spaces",
  "42A": "Harmonic analysis in one variable",
  "42B": "Harmonic analysis in several variables",
  "42C": "Nontrigonometric harmonic analysis",
  "43": "Abstract harmonic analysis",
  "43A": "Abstract harmonic analysis",
  "44": "Integral transforms, operational calculus",
  "44A": "Integral transforms, operational calculus",
  "45": "Integral equations",
  "45A": "Linear integral equations",
  "45B": "Fredholm integral equations",
  "45C": "Eigenvalue problems for integral equations",
  "45D": "Volterra integral equations",
  "45E": "Singular integral equations",
  "45F": "Systems of linear integral equations",
  "45G": "Nonlinear integral equations",
  "45H": "Integral equations with miscellaneous special kernels",
  "45J": "Integro-ordinary differential equations",
  "45K": "Integro-partial differential equations",
  "45L": "Theoretical approximation of solutions to integral equations",
  "45M": "Qualitative behavior of solutions to integral equations",
  "45N": "Abstract integral equations, integral equations in abstract spaces",
  "45P": "Integral operators",
  "45Q": "Inverse problems for integral equations",
  "45R": "Random integral equations",
  "46": "Functional analysis",
  "46A": "Topological linear spaces and related structures",
  "46B": "Normed linear spaces and Banach spaces; Banach lattices",
  "46C": "Inner product spaces and their generalizations, Hilbert spaces",
  "46E": "Linear function spaces and their duals",
  "46F": "Distributions, generalized functions, distribution spaces",
  "46G": "Measures, integration, derivative, holomorphy (all involving infinite-dimensional spaces)",
  "46H": "Topological algebras, normed rings and algebras, Banach algebras",
  "46J": "Commutative Banach algebras and commutative topological algebras",
  "46K": "Topological (rings and) algebras with an involution",
  "46L": "Selfadjoint operator algebras (\\(C^*\\)-algebras, von Neumann (\\(W^*\\)-) algebras, etc.)",
  "46M": "Methods of category theory in functional analysis",
  "46N": "Miscellaneous applications of functional analysis",
  "46S": "Other (nonclassical) types of functional analysis",
  "46T": "Nonlinear functional analysis",
  "47": "Operator theory",
  "47A": "General theory of linear operators",
  "47B": "Special classes of linear operators",
  "47C": "Individual linear operators as elements of algebraic systems",
  "47D": "Groups and semigroups of linear operators, their generalizations and applications",
  "47E": "Ordinary differential operators",
  "47F": "Partial differential operators",
  "47G": "Integral, integro-differential, and pseudodifferential operators",
  "47H": "Nonlinear operators and their properties",
  "47J": "Equations and inequalities involving nonlinear operators",
  "47L": "Linear spaces and algebras of operators",
  "47N": "Miscellaneous applications of operator theory",
  "47S": "Other (nonclassical) types of operator theory",
  "49": "Calculus of variations and optimal control; optimization",
  "49J": "Existence theories in calculus of variations and optimal control",
  "49K": "Optimality conditions",
  "49L": "Hamilton-Jacobi theories",
  "49M": "Numerical methods in optimal control",
  "49N": "Miscellaneous topics in calculus of variations and optimal control",
  "49Q": "Manifolds and measure-geometric topics",
  "49R": "Variational methods for eigenvalues of operators",
  "49S": "Variational principles of physics",
  "51": "Geometry",
  "51A": "Linear incidence geometry",
  "51B": "Nonlinear incidence geometry",
  "51C": "Ring geometry (Hjelmslev, Barbilian, etc.)",
  "51D": "Geometric closure systems",
  "51E": "Finite geometry and special incidence structures",
  "51F": "Metric geometry",
  "51G": "Ordered geometries (ordered incidence structures, etc.)",
  "51H": "Topological geometry",
  "51J": "Incidence groups",
  "51K": "Distance geometry",
  "51L": "Geometric order structures",
  "51M": "Real and complex geometry",
  "51N": "Analytic and descriptive geometry",
  "51P": "Classical or axiomatic geometry and physics",
  "52": "Convex and discrete geometry",
  "52A": "General convexity",
  "52B": "Polytopes and polyhedra",
  "52C": "Discrete geometry",
  "53": "Differential geometry",
  "53A": "Classical differential geometry",
  "53B": "Local differential geometry",
  "53C": "Global differential geometry",
  "53D": "Symplectic geometry, contact geometry",
  "53E": "Geometric evolution equations",
  "53Z": "Applications of differential geometry to sciences and engineering",
  "54": "General topology",
  "54A": "Generalities in topology",
  "54B": "Basic constructions in general topology",
  "54C": "Maps and general types of topological spaces defined by maps",
  "54D": "Fairly general properties of topological spaces",
  "54E": "Topological spaces with richer structures",
  "54F": "Special properties of topological spaces",
  "54G": "Peculiar topological spaces",
  "54H": "Connections of general topology with other structures, applications",
  "54J": "Nonstandard topology",
  "55": "Algebraic topology",
  "55M": "Classical topics in algebraic topology",
  "55N": "Homology and cohomology theories in algebraic topology",
  "55P": "Homotopy theory",
  "55Q": "Homotopy groups",
  "55R": "Fiber spaces and bundles in algebraic topology",
  "55S": "Operations and obstructions in algebraic topology",
  "55T": "Spectral sequences in algebraic topology",
  "55U": "Applied homological algebra and category theory in algebraic topology",
  "57": "Manifolds and cell complexes",
  "57K": "Low-dimensional topology in specific dimensions",
  "57M": "General low-dimensional topology",
  "57N": "Topological manifolds",
  "57P": "Generalized manifolds",
  "57Q": "PL-topology",
  "57R": "Differential topology",
  "57S": "Topological transformation groups",
  "57T": "Homology and homotopy of topological groups and related structures",
  "57Z": "Relations of manifolds and cell complexes with science and engineering",
  "58": "Global analysis, analysis on manifolds",
  "58A": "General theory of differentiable manifolds",
  "58B": "Infinite-dimensional manifolds",
  "58C": "Calculus on manifolds; nonlinear operators",
  "58D": "Spaces and manifolds of mappings (including nonlinear versions of 46Exx)",
  "58E": "Variational problems in infinite-dimensional spaces",
  "58H": "Pseudogroups, differentiable groupoids and general structures on manifolds",
  "58J": "Partial differential equations on manifolds; differential operators",
  "58K": "Theory of singularities and catastrophe theory",
  "58Z": "Applications of global analysis to the sciences",
  "60": "Probability theory and stochastic processes",
  "60A": "Foundations of probability theory",
  "60B": "Probability theory on algebraic and topological structures",
  "60C": "Combinatorial probability",
  "60D": "Geometric probability and stochastic geometry",
  "60E": "Distribution theory",
  "60F": "Limit theorems in probability theory",
  "60G": "Stochastic processes",
  "60H": "Stochastic analysis",
  "60J": "Markov processes",
  "60K": "Special processes",
  "60L": "Rough analysis",
  "62": "Statistics",
  "62A": "Foundational topics in statistics",
  "62B": "Sufficiency and information",
  "62C": "Statistical decision theory",
  "62D": "Statistical sampling theory and related topics",
  "62E": "Statistical distribution theory",
  "62F": "Parametric inference",
  "62G": "Nonparametric inference",
  "62H": "Multivariate analysis",
  "62J": "Linear inference, regression",
  "62K": "Design of statistical experiments",
  "62L": "Sequential statistical methods",
  "62M": "Inference from stochastic processes",
  "62N": "Survival analysis and censored data",
  "62P": "Applications of statistics",
  "62Q": "Statistical tables",
  "62R": "Statistics on algebraic and topological structures",
  "65": "Numerical analysis",
  "65A": "Tables in numerical analysis",
  "65B": "Acceleration of convergence in numerical analysis",
  "65C": "Probabilistic methods, stochastic differential equations",
  "65D": "Numerical approximation and computational geometry (primarily algorithms)",
  "65E": "Numerical methods in complex analysis (potential theory, etc.)",
  "65F": "Numerical linear algebra",
  "65G": "Error analysis and interval analysis",
  "65H": "Nonlinear algebraic or transcendental equations",
  "65J": "Numerical analysis in abstract spaces",
  "65K": "Numerical methods for mathematical programming, optimization and variational techniques",
  "65L": "Numerical methods for ordinary differential equations",
  "65M": "Numerical methods for partial differential equations, initial value and time-dependent initial-boundary value problems",
  "65N": "Numerical methods for partial differential equations, boundary value problems",
  "65P": "Numerical problems in dynamical systems",
  "65Q": "Numerical methods for difference and functional equations, recurrence relations",
  "65R": "Numerical methods for integral equations, integral transforms",
  "65S": "Graphical methods in numerical analysis",
  "65T": "Numerical methods in Fourier analysis",
  "65Y": "Computer aspects of numerical algorithms",
  "65Z": "Applications to the sciences",
  "68": "Computer science",
  "68M": "Computer system organization",
  "68N": "Theory of software",
  "68P": "Theory of data",
  "68Q": "Theory of computing",
  "68R": "Discrete mathematics in relation to computer science",
  "68T": "Artificial intelligence",
  "68U": "Computing methodologies and applications",
  "68V": "Computer science support for mathematical research and practice",
  "68W": "Algorithms in computer science",
  "70": "Mechanics of particles and systems",
  "70A": "Axiomatics, foundations",
  "70B": "Kinematics",
  "70C": "Statics",
  "70E": "Dynamics of a rigid body and of multibody systems",
  "70F": "Dynamics of a system of particles, including celestial mechanics",
  "70G": "General models, approaches, and methods in mechanics of particles and systems",
  "70H": "Hamiltonian and Lagrangian mechanics",
  "70J": "Linear vibration theory",
  "70K": "Nonlinear dynamics in mechanics",
  "70L": "Random and stochastic aspects of the mechanics of particles and systems",
  "70M": "Orbital mechanics",
  "70P": "Variable mass, rockets",
  "70Q": "Control of mechanical systems",
  "70S": "Classical field theories",
  "74": "Mechanics of deformable solids",
  "74A": "Generalities, axiomatics, foundations of continuum mechanics of solids",
  "74B": "Elastic materials",
  "74C": "Plastic materials, materials of stress-rate and internal-variable type",
  "74D": "Materials of strain-rate type and history type, other materials with memory (including elastic materials with viscous damping, various viscoelastic materials)",
  "74E": "Material properties given special treatment",
  "74F": "Coupling of solid mechanics with other effects",
  "74G": "Equilibrium (steady-state) problems in solid mechanics",
  "74H": "Dynamical problems in solid mechanics",
  "74J": "Waves in solid mechanics",
  "74K": "Thin bodies, structures",
  "74L": "Special subfields of solid mechanics",
  "74M": "Special kinds of problems in solid mechanics",
  "74N": "Phase transformations in solids",
  "74P": "Optimization problems in solid mechanics",
  "74Q": "Homogenization, determination of effective properties in solid mechanics",
  "74R": "Fracture and damage",
  "74S": "Numerical and other methods in solid mechanics",
  "76": "Fluid mechanics",
  "76A": "Foundations, constitutive equations, rheology, hydrodynamical models of non-fluid phenomena",
  "76B": "Incompressible inviscid fluids",
  "76D": "Incompressible viscous fluids",
  "76E": "Hydrodynamic stability",
  "76F": "Turbulence",
  "76G": "General aerodynamics and subsonic flows",
  "76H": "Transonic flows",
  "76J": "Supersonic flows",
  "76K": "Hypersonic flows",
  "76L": "Shock waves and blast waves in fluid mechanics",
  "76M": "Basic methods in fluid mechanics",
  "76N": "Compressible fluids and gas dynamics",
  "76P": "Rarefied gas flows, Boltzmann equation in fluid mechanics",
  "76Q": "Hydro- and aero-acoustics",
  "76R": "Diffusion and convection",
  "76S": "Flows in porous media; filtration; seepage",
  "76T": "Multiphase and multicomponent flows",
  "76U": "Rotating fluids",
  "76V": "Reaction effects in flows",
  "76W": "Magnetohydrodynamics and electrohydrodynamics",
  "76X": "Ionized gas flow in electromagnetic fields; plasmic flow",
  "76Y": "Quantum hydrodynamics and relativistic hydrodynamics",
  "76Z": "Biological fluid mechanics",
  "78": "Optics, electromagnetic theory",
  "78A": "General topics in optics and electromagnetic theory",
  "78M": "Basic methods for problems in optics and electromagnetic theory",
  "80": "Classical thermodynamics, heat transfer",
  "80A": "Thermodynamics and heat transfer",
  "80M": "Basic methods in thermodynamics and heat transfer",
  "81": "Quantum theory",
  "81P": "Foundations, quantum information and its processing, quantum axioms, and philosophy",
  "81Q": "General mathematical topics and methods in quantum theory",
  "81R": "Groups and algebras in quantum theory",
  "81S": "General quantum mechanics and problems of quantization",
  "81T": "Quantum field theory; related classical field theories",
  "81U": "Quantum scattering theory",
  "81V": "Applications of quantum theory to specific physical systems",
  "82": "Statistical mechanics, structure of matter",
  "82B": "Equilibrium statistical mechanics",
  "82C": "Time-dependent statistical mechanics (dynamic and nonequilibrium)",
  "82D": "Applications of statistical mechanics to specific types of physical systems",
  "82M": "Basic methods in statistical mechanics",
  "83": "Relativity and gravitational theory",
  "83A": "Special relativity",
  "83B": "Observational and experimental questions in relativity and gravitational theory",
  "83C": "General relativity",
  "83D": "Relativistic gravitational theories other than Einstein's, including asymmetric field theories",
  "83E": "Unified, higher-dimensional and super field theories",
  "83F": "Relativistic cosmology",
  "85": "Astronomy and astrophysics",
  "85A": "Astronomy and astrophysics",
  "86": "Geophysics",
  "86A": "Geophysics",
  "90": "Operations research, mathematical programming",
  "90B": "Operations research and management science",
  "90C": "Mathematical programming",
  "91": "Game theory, economics, finance, and other social and behavioral sciences",
  "91A": "Game theory",
  "91B": "Mathematical economics",
  "91C": "Social and behavioral sciences: general topics",
  "91D": "Mathematical sociology (including anthropology)",
  "91E": "Mathematical psychology",
  "91F": "Other social and behavioral sciences (mathematical treatment)",
  "91G": "Actuarial science and mathematical finance",
  "92": "Biology and other natural sciences",
  "92B": "Mathematical biology in general",
  "92C": "Physiological, cellular and medical topics",
  "92D": "Genetics and population dynamics",
  "92E": "Chemistry",
  "92F": "Other natural sciences (mathematical treatment)",
  "93": "Systems theory; control",
  "93A": "General systems theory",
  "93B": "Controllability, observability, and system structure",
  "93C": "Model systems in control theory",
  "93D": "Stability of control systems",
  "93E": "Stochastic systems and control",
  "94": "Information and communication theory, circuits",
  "94A": "Communication, information",
  "94B": "Theory of error-correcting codes and error-detecting codes",
  "94C": "Circuits, networks",
  "94D": "Miscellaneous topics in information and communication theory",
  "97": "Mathematics education",
  "97A": "History and society (aspects of mathematics education)",
  "97B": "Educational policy and systems",
  "97C": "Psychology of mathematics education, research in mathematics education",
  "97D": "Education and instruction in mathematics",
  "97E": "Education of foundations of mathematics",
  "97F": "Education of arithmetic and number theory",
  "97G": "Geometry education",
  "97H": "Algebra education",
  "97I": "Analysis education",
  "97K": "Education of combinatorics, graph theory, probability theory, and statistics",
  "97M": "Education of mathematical modeling and applications of mathematics",
  "97N": "Education of numerical mathematics",
  "97P": "Computer science (educational aspects)",
  "97U": "Educational material and media and educational technology in mathematics education"
};
