# backend/src/utils/math/render_helpers.py

import re
import html as html_lib
import hashlib
from urllib.parse import quote


PSPICTURE_RE = re.compile(
    r"\\begin\{pspicture\}[\s\S]*?\\end\{pspicture\}",
    re.MULTILINE
)


def hash_pstricks_block(block: str) -> str:
    return hashlib.sha256(block.encode("utf-8")).hexdigest()[:16]


def extract_pstricks_blocks(tex: str) -> list[str]:
    return PSPICTURE_RE.findall(tex or "")


def extract_pstricks_hashes(tex: str) -> list[str]:
    return [
        hash_pstricks_block(block)
        for block in extract_pstricks_blocks(tex)
    ]


def get_svg_filename(svg_path: str) -> str | None:
    if not svg_path:
        return None

    clean_path = str(svg_path).replace("\\", "/").rstrip("/")
    return clean_path.split("/")[-1]


def make_diagram_img_tag(svg_filename: str) -> str:
    if not svg_filename:
        return '<div class="img-placeholder"><em>[Diagram path missing.]</em></div>'

    return (
        '<div class="math-diagram-wrap">'
        f'<img src="http://127.0.0.1:5000/api/math/diagrams/{svg_filename}" '
        'class="math-diagram" '
        'alt="Mathematical diagram">'
        '</div>'
    )


def render_pmlinkname(match: re.Match) -> str:
    link_text = match.group(1).strip()
    target_slug = match.group(2).strip()

    return (
        f'<a class="math-explicit-link" '
        f'href="concept.html?slug={quote(target_slug)}">'
        f'{html_lib.escape(link_text)}</a>'
    )


def render_latex_list_block(match: re.Match) -> str:
    """
    Convert one LaTeX itemize/enumerate block into an HTML list.

    This function assumes nested itemize/enumerate blocks have already been
    converted to HTML, so splitting on \\item is safe.
    """
    env_name = match.group(1).lower()
    body = match.group(2).strip()

    html_tag = "ul" if env_name == "itemize" else "ol"

    if not body:
        return match.group(0)

    # Normalize optional labels:
    # \item[foo] text  ->  \item text
    body = re.sub(
        r"\\item\s*\[[^\]]*\]",
        r"\\item",
        body,
        flags=re.IGNORECASE,
    )

    raw_items = re.split(
        r"\\item\b",
        body,
        flags=re.IGNORECASE,
    )

    items = []

    for raw_item in raw_items:
        cleaned = raw_item.strip()

        if not cleaned:
            continue

        items.append(f"<li>{cleaned}</li>")

    if not items:
        return match.group(0)

    return (
        f"<{html_tag}>\n"
        + "\n".join(items)
        + f"\n</{html_tag}>"
    )


def render_latex_lists_to_html(html: str) -> str:
    """
    Convert LaTeX itemize/enumerate environments into HTML lists.

    Important:
        This converts innermost list blocks first so nested lists do not confuse
        the regex matcher.
    """
    list_block_pattern = re.compile(
        r"\\begin\{(itemize|enumerate)\}"
        r"((?:(?!\\begin\{(?:itemize|enumerate)\}).)*?)"
        r"\\end\{\1\}",
        flags=re.IGNORECASE | re.DOTALL,
    )

    previous = None

    while previous != html:
        previous = html
        html = list_block_pattern.sub(render_latex_list_block, html)

    return html


def remove_empty_html_list_items(html: str) -> str:
    """
    Remove empty HTML list items generated by odd LaTeX list structures.

    This is a safety net, not the main list parser.
    """
    return re.sub(
        r"\s*<li>\s*</li>\s*",
        "\n",
        html,
        flags=re.IGNORECASE,
    )


def render_prose_latex_to_html(tex: str) -> str:
    if not tex:
        return ""

    html = tex.replace("\r\n", "\n").replace("\r", "\n")

    html = render_latex_lists_to_html(html)

    html = re.sub(
        r"\\PMlinkname\{([^{}]+)\}\{([^{}]+)\}",
        render_pmlinkname,
        html,
        flags=re.DOTALL,
    )

    html = re.sub(
        r"\\PMlinkescapetext\{([^{}]*)\}",
        r'<span class="math-no-autolink">\1</span>',
        html,
        flags=re.DOTALL,
    )

    html = re.sub(
        r"\\textbf\{([^{}]*)\}",
        r"<strong>\1</strong>",
        html,
        flags=re.DOTALL,
    )

    html = re.sub(
        r"\\emph\{([^{}]*)\}",
        r"<em>\1</em>",
        html,
        flags=re.DOTALL,
    )

    html = re.sub(
        r"\{\\em\s+([^{}]*)\}",
        r"<em>\1</em>",
        html,
        flags=re.DOTALL,
    )

    html = re.sub(
        r"\{\\bf\s+([^{}]*)\}",
        r"<strong>\1</strong>",
        html,
        flags=re.DOTALL,
    )

    html = re.sub(r"\\\\[ \t]*(?:\n[ \t]*){2,}", "\n\n", html)
    html = re.sub(r"\\\\[ \t]*", "<br>\n", html)

    html = remove_empty_html_list_items(html)

    parts = re.split(r"\n\s*\n+", html.strip())
    paragraphs = []

    for part in parts:
        cleaned = part.strip()
        if cleaned:
            paragraphs.append(f"<p>{cleaned}</p>")

    return "\n\n".join(paragraphs)