# backend/src/utils/math/render_helpers.py

import re
import html as html_lib
import hashlib
from urllib.parse import quote


PSPICTURE_RE = re.compile(
    r"\\begin\{pspicture\}[\s\S]*?\\end\{pspicture\}",
    re.MULTILINE
)


def hash_pstricks_block(block: str) -> str:
    return hashlib.sha256(block.encode("utf-8")).hexdigest()[:16]


def extract_pstricks_blocks(tex: str) -> list[str]:
    return PSPICTURE_RE.findall(tex or "")


def extract_pstricks_hashes(tex: str) -> list[str]:
    return [
        hash_pstricks_block(block)
        for block in extract_pstricks_blocks(tex)
    ]


def get_svg_filename(svg_path: str) -> str | None:
    if not svg_path:
        return None

    clean_path = str(svg_path).replace("\\", "/").rstrip("/")
    return clean_path.split("/")[-1]


def make_diagram_img_tag(svg_filename: str) -> str:
    if not svg_filename:
        return '<div class="img-placeholder"><em>[Diagram path missing.]</em></div>'

    return (
        '<div class="math-diagram-wrap">'
        f'<img src="http://127.0.0.1:5000/api/math/diagrams/{svg_filename}" '
        'class="math-diagram" '
        'alt="Mathematical diagram">'
        '</div>'
    )


def render_pmlinkname(match: re.Match) -> str:
    link_text = match.group(1).strip()
    target_slug = match.group(2).strip()

    return (
        f'<a class="math-explicit-link" '
        f'href="concept.html?slug={quote(target_slug)}">'
        f'{html_lib.escape(link_text)}</a>'
    )


def render_latex_list_block(match: re.Match) -> str:
    """
    Convert one LaTeX itemize/enumerate block into an HTML list.

    This function assumes nested itemize/enumerate blocks have already been
    converted to HTML, so splitting on \\item is safe.
    """
    env_name = match.group(1).lower()
    body = match.group(2).strip()

    html_tag = "ul" if env_name == "itemize" else "ol"

    if not body:
        return match.group(0)

    # Normalize optional labels:
    # \item[foo] text  ->  \item text
    body = re.sub(
        r"\\item\s*\[[^\]]*\]",
        r"\\item",
        body,
        flags=re.IGNORECASE,
    )

    raw_items = re.split(
        r"\\item\b",
        body,
        flags=re.IGNORECASE,
    )

    items = []

    for raw_item in raw_items:
        cleaned = raw_item.strip()

        if not cleaned:
            continue

        items.append(f"<li>{cleaned}</li>")

    if not items:
        return match.group(0)

    return (
        f"<{html_tag}>\n"
        + "\n".join(items)
        + f"\n</{html_tag}>"
    )


def render_latex_lists_to_html(html: str) -> str:
    """
    Convert LaTeX itemize/enumerate environments into HTML lists.

    Important:
        This converts innermost list blocks first so nested lists do not confuse
        the regex matcher.
    """
    list_block_pattern = re.compile(
        r"\\begin\{(itemize|enumerate)\}"
        r"((?:(?!\\begin\{(?:itemize|enumerate)\}).)*?)"
        r"\\end\{\1\}",
        flags=re.IGNORECASE | re.DOTALL,
    )

    previous = None

    while previous != html:
        previous = html
        html = list_block_pattern.sub(render_latex_list_block, html)

    return html


def remove_empty_html_list_items(html: str) -> str:
    """
    Remove empty HTML list items generated by odd LaTeX list structures.

    This is a safety net, not the main list parser.
    """
    return re.sub(
        r"\s*<li>\s*</li>\s*",
        "\n",
        html,
        flags=re.IGNORECASE,
    )


def render_latex_bibliography_block(match: re.Match) -> str:
    """
    Convert a LaTeX thebibliography block into an HTML references section.

    Handles:
        \\bibitem{key} Reference text
        \\bibitem[Label]{key} Reference text

    Fail-safe rule:
        If parsing fails, return the original LaTeX block.
    """
    original_block = match.group(0)
    body = match.group(1).strip()

    if not body:
        return original_block

    bibitem_pattern = re.compile(
        r"\\bibitem(?:\[[^\]]*\])?\{([^{}]*)\}\s*",
        flags=re.IGNORECASE,
    )

    bibitem_matches = list(bibitem_pattern.finditer(body))

    if not bibitem_matches:
        return original_block

    items = []

    for index, bib_match in enumerate(bibitem_matches):
        item_start = bib_match.end()

        if index + 1 < len(bibitem_matches):
            item_end = bibitem_matches[index + 1].start()
        else:
            item_end = len(body)

        cleaned = body[item_start:item_end].strip()

        if cleaned:
            items.append(f"<li>{cleaned}</li>")

    if not items:
        return original_block

    return (
        '<section class="math-bibliography">\n'
        '<h3>References</h3>\n'
        '<ol>\n'
        + "\n".join(items)
        + "\n</ol>\n"
        "</section>"
    )


def render_latex_bibliography_to_html(html: str) -> str:
    """
    Convert LaTeX thebibliography environments into an HTML references section.
    """
    return re.sub(
        r"\\begin\{thebibliography\}(?:\{[^{}]*\})?([\s\S]*?)\\end\{thebibliography\}",
        render_latex_bibliography_block,
        html,
        flags=re.IGNORECASE,
    )


def clean_latex_table_cell(cell: str) -> str:
    """
    Clean one LaTeX table cell before wrapping it in <td>.
    """
    cell = cell.strip()

    # Defensive cleanup in case previously-rendered HTML sneaks in.
    cell = re.sub(r"</?p[^>]*>", "", cell, flags=re.IGNORECASE)
    cell = re.sub(r"<br\s*/?>", "", cell, flags=re.IGNORECASE)

    # Remove table rule commands that should not be visible as text.
    cell = re.sub(r"\\hline\b", "", cell, flags=re.IGNORECASE)
    cell = re.sub(r"\\cline\{[^{}]*\}", "", cell, flags=re.IGNORECASE)

    return cell.strip()


def render_latex_tabular_block(match: re.Match) -> str:
    """
    Convert a simple LaTeX tabular environment into an HTML table.

    This intentionally handles the common PlanetMath-style cases:
        \\begin{tabular}{|c|c|}
        \\hline
        A & B \\\\
        \\hline
        1 & 2
        \\end{tabular}

    Fail-safe rule:
        If parsing produces no usable rows, return the original block.
    """
    original_block = match.group(0)
    body = match.group(2).strip()

    if not body:
        return original_block

    # Defensive cleanup in case this function is ever run on already-rendered text.
    body = re.sub(
        r"<br\s*/?>\s*</p>\s*<p[^>]*>",
        r"\\\\",
        body,
        flags=re.IGNORECASE,
    )
    body = re.sub(r"</?p[^>]*>", "", body, flags=re.IGNORECASE)
    body = re.sub(r"<br\s*/?>", r"\\\\", body, flags=re.IGNORECASE)

    # Split rows on LaTeX row breaks.
    raw_rows = re.split(
        r"\\\\(?:\s*\[[^\]]*\])?",
        body,
        flags=re.IGNORECASE,
    )

    html_rows = []

    for raw_row in raw_rows:
        row = raw_row.strip()

        if not row:
            continue

        row = re.sub(r"\\hline\b", "", row, flags=re.IGNORECASE)
        row = re.sub(r"\\cline\{[^{}]*\}", "", row, flags=re.IGNORECASE)
        row = row.strip()

        if not row:
            continue

        raw_cells = row.split("&")
        cells = [clean_latex_table_cell(cell) for cell in raw_cells]

        # Avoid creating empty junk rows.
        if not any(cells):
            continue

        html_cells = "".join(f"<td>{cell}</td>" for cell in cells)

        html_rows.append(f"<tr>{html_cells}</tr>")

    if not html_rows:
        return original_block

    return (
        '<div class="math-table-wrapper">\n'
        '<table class="math-table">\n'
        '<tbody>\n'
        + "\n".join(html_rows)
        + "\n</tbody>\n"
        "</table>\n"
        "</div>"
    )


def render_latex_tabular_to_html(html: str) -> str:
    """
    Convert simple LaTeX tabular environments into HTML tables.
    """
    return re.sub(
        r"\\begin\{tabular\}(\{[^{}]*\})?([\s\S]*?)\\end\{tabular\}",
        render_latex_tabular_block,
        html,
        flags=re.IGNORECASE,
    )


SIMPLE_BLOCK_ENVIRONMENTS = {
    "center": ("div", "math-center"),
    "quote": ("blockquote", "math-quote"),
}


def render_simple_latex_block_environment(match: re.Match) -> str:
    """
    Convert simple display/block LaTeX environments into HTML wrappers.

    Examples:
        \\begin{center} ... \\end{center}
        \\begin{quote} ... \\end{quote}
    """
    original_block = match.group(0)
    env_name = match.group(1).lower()
    body = match.group(2).strip()

    if env_name not in SIMPLE_BLOCK_ENVIRONMENTS or not body:
        return original_block

    html_tag, css_class = SIMPLE_BLOCK_ENVIRONMENTS[env_name]

    return (
        f'<{html_tag} class="{css_class}">\n'
        f'{body}\n'
        f'</{html_tag}>'
    )


def render_simple_latex_block_environments_to_html(html: str) -> str:
    """
    Convert simple non-math LaTeX block environments into HTML.
    """
    env_names = "|".join(
        re.escape(name)
        for name in sorted(SIMPLE_BLOCK_ENVIRONMENTS.keys(), key=len, reverse=True)
    )

    pattern = re.compile(
        rf"\\begin\{{({env_names})\}}([\s\S]*?)\\end\{{\1\}}",
        flags=re.IGNORECASE,
    )

    return pattern.sub(render_simple_latex_block_environment, html)


THEOREM_LIKE_ENVIRONMENTS = {
    "proof": "Proof",
    "prop": "Proposition",
    "thm": "Theorem",
    "thm*": "Theorem",
    "theorem": "Theorem",
    "lem": "Lemma",
    "lemma": "Lemma",
    "lemma*": "Lemma",
    "cor": "Corollary",
    "defn": "Definition",
    "definition": "Definition",
    "rem": "Remark",
    "example": "Example",
    "example*": "Example",
}


def render_latex_named_environment_block(match: re.Match) -> str:
    """
    Convert theorem/proof-like LaTeX environments into semantic HTML blocks.

    Example:
        \\begin{proof}
        ...
        \\end{proof}

    becomes:
        <section class="math-env math-env-proof">
        <div class="math-env-label">Proof.</div>
        <div class="math-env-body">...</div>
        </section>
    """
    original_block = match.group(0)
    env_name = match.group(1)
    body = match.group(2).strip()

    env_key = env_name.lower()
    label = THEOREM_LIKE_ENVIRONMENTS.get(env_key)

    if not label or not body:
        return original_block

    css_key = re.sub(r"[^a-z0-9]+", "-", env_key).strip("-")

    return (
        f'<section class="math-env math-env-{css_key}">\n'
        f'<div class="math-env-label">{label}.</div>\n'
        f'<div class="math-env-body">\n{body}\n</div>\n'
        f'</section>'
    )


def render_latex_named_environments_to_html(html: str) -> str:
    """
    Convert theorem/proof-like LaTeX environments into HTML.

    This intentionally does not touch MathJax environments like equation,
    align, pmatrix, array, cases, etc.
    """
    env_names = "|".join(
        re.escape(name)
        for name in sorted(THEOREM_LIKE_ENVIRONMENTS.keys(), key=len, reverse=True)
    )

    pattern = re.compile(
        rf"\\begin\{{({env_names})\}}([\s\S]*?)\\end\{{\1\}}",
        flags=re.IGNORECASE,
    )

    return pattern.sub(render_latex_named_environment_block, html)


def render_latex_description_block(match: re.Match) -> str:
    """
    Convert a LaTeX description environment into an HTML description list.

    Example:
        \\begin{description}
        \\item[Term] Explanation
        \\item[Other] More explanation
        \\end{description}

    becomes:
        <dl class="math-description-list">
        <dt>Term</dt>
        <dd>Explanation</dd>
        ...
        </dl>
    """
    original_block = match.group(0)
    body = match.group(1).strip()

    if not body:
        return original_block

    item_pattern = re.compile(
        r"\\item(?:\s*\[([^\]]*)\])?\s*",
        flags=re.IGNORECASE,
    )

    item_matches = list(item_pattern.finditer(body))

    if not item_matches:
        return original_block

    entries = []

    for index, item_match in enumerate(item_matches):
        label = (item_match.group(1) or "").strip()
        item_start = item_match.end()

        if index + 1 < len(item_matches):
            item_end = item_matches[index + 1].start()
        else:
            item_end = len(body)

        description = body[item_start:item_end].strip()

        if not label and not description:
            continue

        if label:
            entries.append(f"<dt>{label}</dt>")
            entries.append(f"<dd>{description}</dd>")
        else:
            entries.append(f"<dd>{description}</dd>")

    if not entries:
        return original_block

    return (
        '<dl class="math-description-list">\n'
        + "\n".join(entries)
        + "\n</dl>"
    )


def render_latex_description_to_html(html: str) -> str:
    """
    Convert LaTeX description environments into HTML description lists.
    """
    return re.sub(
        r"\\begin\{description\}([\s\S]*?)\\end\{description\}",
        render_latex_description_block,
        html,
        flags=re.IGNORECASE,
    )


def render_prose_latex_to_html(tex: str) -> str:
    if not tex:
        return ""

    html = tex.replace("\r\n", "\n").replace("\r", "\n")

    html = render_latex_lists_to_html(html)
    html = render_latex_description_to_html(html)
    html = render_latex_tabular_to_html(html)
    html = render_latex_bibliography_to_html(html)
    html = render_latex_named_environments_to_html(html)
    html = render_simple_latex_block_environments_to_html(html)

    html = re.sub(
        r"\\PMlinkname\{([^{}]+)\}\{([^{}]+)\}",
        render_pmlinkname,
        html,
        flags=re.DOTALL,
    )

    html = re.sub(
        r"\\PMlinkescapetext\{([^{}]*)\}",
        r'<span class="math-no-autolink">\1</span>',
        html,
        flags=re.DOTALL,
    )

    html = re.sub(
        r"\\textbf\{([^{}]*)\}",
        r"<strong>\1</strong>",
        html,
        flags=re.DOTALL,
    )

    html = re.sub(
        r"\\emph\{([^{}]*)\}",
        r"<em>\1</em>",
        html,
        flags=re.DOTALL,
    )

    html = re.sub(
        r"\{\\em\s+([^{}]*)\}",
        r"<em>\1</em>",
        html,
        flags=re.DOTALL,
    )

    html = re.sub(
        r"\\textit\{([^{}]*)\}",
        r"<em>\1</em>",
        html,
        flags=re.DOTALL,
    )

    html = re.sub(
        r"\{\\it\s+([^{}]*)\}",
        r"<em>\1</em>",
        html,
        flags=re.DOTALL,
    )

    html = re.sub(
        r"\{\\bf\s+([^{}]*)\}",
        r"<strong>\1</strong>",
        html,
        flags=re.DOTALL,
    )

    html = re.sub(r"\\\\[ \t]*(?:\n[ \t]*){2,}", "\n\n", html)
    html = re.sub(r"\\\\[ \t]*", "<br>\n", html)

    html = remove_empty_html_list_items(html)

    parts = re.split(r"\n\s*\n+", html.strip())
    paragraphs = []

    for part in parts:
        cleaned = part.strip()
        if cleaned:
            paragraphs.append(f"<p>{cleaned}</p>")

    return "\n\n".join(paragraphs)