"""Eight new entries each in group theory, ring theory, and set theory.

Reviewed titles, aliases, defined terms, and source mentions before selection.
Existing ordinal, rank, regular/singular cardinal and power-set definitions
were not duplicated. Qualified names avoid relational transitive closure.
"""
import argparse
from collections import Counter
from datetime import datetime
from pathlib import Path
import re
import sqlite3
from add_five_and_snake_lemmas import (
    SRC, source, document_types, create_math_concept,
    fetch_public_math_concept_detail, search_public_math_library, relate, links,
)
from add_twenty_concepts_20260922 import ESCAPES

GROUP_REF = ('J. S. Milne', 'Group Theory', 'https://jmilne.org/math/CourseNotes/GTe6.pdf')
SET_REF = ('William A. R. Weiss', 'An Introduction to Set Theory', 'https://www.math.utoronto.ca/weiss/set_theory.pdf')
AD_REF = ('Lorenz Halbeisen', 'Combinatorial Set Theory, almost disjoint families', 'https://people.math.ethz.ch/~halorenz/publications/pdf/cst.pdf')
def stacks(tag, title):
    return ('The Stacks Project', title, 'https://stacks.math.columbia.edu/tag/' + tag)

ENTRIES = []
def add(area, title, slug, codes, aliases, definitions, related, body, reference=None):
    ENTRIES.append(dict(area=area,title=title,slug=slug,
        canonical=''.join(w.capitalize() for w in slug.split('-')),
        classifications=codes.split(), synonyms=aliases, definitions=definitions,
        related=related.split(), body=body,
        reference=reference or (GROUP_REF if area=='group' else SET_REF),
        escapes=list(ESCAPES)+['type','types','field','fields','measure','projection',
            'transitive','maximal ideal','prime ideal','normal closure','linear map',
            'symmetric','nor','insertion','deletion','instance','reduced','separating',
            'eventually','injective','embedding','span','transitive closure','rank',
            'acyclic','height','strong','theory']))

add('group','nilpotent group','nilpotent-group','20F18 20F14',[],
    ['lower central series','nilpotency class'], 'group commutator-subgroup center-of-a-group solvable-group',r"""
\begin{definition}
For subgroups \(H,K\) of a group, let \([H,K]\) be generated by the commutators \([h,k]=h^{-1}k^{-1}hk\). The \emph{lower central series} of \(G\) is
\[
\gamma_1(G)=G,\qquad \gamma_{n+1}(G)=[\gamma_n(G),G].
\]
The group is \emph{nilpotent} if \(\gamma_{c+1}(G)=1\) for some nonnegative integer \(c\). The smallest such \(c\) is its \emph{nilpotency class}. The trivial group has class zero; a nontrivial abelian group has class one.
\end{definition}
\begin{example}
The quaternion group \(Q_8=\{1,-1,i,-i,j,-j,k,-k\}\), with \(i^2=j^2=k^2=ijk=-1\), has class two. Its commutator subgroup is \(\{1,-1\}\): the quotient by this subgroup is abelian, and \([i,j]=-1\). This subgroup is central, so \(\gamma_3(Q_8)=1\).
\end{example}
\begin{proposition}
Every nontrivial nilpotent group has nontrivial center.
\end{proposition}
\begin{proof}
If its class is \(c\ge1\), then \(\gamma_c(G)\ne1\), whereas \([\gamma_c(G),G]=1\). Thus \(\gamma_c(G)\) is contained in the center.
\end{proof}
\begin{remark}
The [[commutator-subgroup|derived series]] repeatedly takes commutators within the preceding subgroup, whereas the lower central series takes commutators with all of \(G\). These are different constructions. The symmetric group \(S_3\), whose center is trivial, is not nilpotent.
\end{remark}
""")

add('group','torsion group','torsion-group','20F50',['periodic group'],[],
    'group locally-finite-group torsion-free-group',r"""
\begin{definition}
A \emph{torsion group}, also called a \emph{periodic group}, is a group in which every element has finite order: for each \(g\) there is an integer \(n\ge1\), possibly depending on \(g\), such that \(g^n=1\).
\end{definition}
\begin{example}
Every finite group is torsion. The additive group \(\mathbb{Q}/\mathbb{Z}\) is an infinite torsion group: the coset of \(a/b\) is killed by \(b\). Orders in this group have no common finite bound, since \(1/n+\mathbb{Z}\) has order \(n\).
\end{example}
\begin{proposition}
Subgroups and homomorphic images of torsion groups are torsion. Every [[locally-finite-group|locally finite group]] is torsion.
\end{proposition}
\begin{proof}
An equation \(g^n=1\) remains true in a subgroup containing \(g\), and applying a homomorphism gives the corresponding equation for its image. In a locally finite group, the subgroup generated by one element is finite, so that element has finite order.
\end{proof}
\begin{remark}
Do not confuse a torsion group with a group of bounded exponent, where a single positive integer must work for all elements. Nor does being torsion assert that the group itself is finite.
\end{remark}
""")

add('group','torsion-free group','torsion-free-group','20F99',['torsion free group'],[],
    'group torsion-group free-group',r"""
\begin{definition}
A group \(G\) is \emph{torsion-free} if \(g^n=1\), for \(n\ge1\), implies \(g=1\). Equivalently, every nonidentity element has infinite order. For an additive abelian group this condition reads \(nx=0\Rightarrow x=0\).
\end{definition}
\begin{example}
The additive groups \(\mathbb{Z}\) and \(\mathbb{Q}\) are torsion-free. The trivial group is both torsion-free and torsion. No other torsion group is torsion-free.
\end{example}
\begin{proposition}
Subgroups and arbitrary direct products of torsion-free groups are torsion-free, but quotients need not be.
\end{proposition}
\begin{proof}
The defining implication is inherited by a subgroup. In a direct product, \((g_i)^n=1\) implies \(g_i^n=1\) in every coordinate, hence all \(g_i=1\). On the other hand, \(\mathbb{Z}\) is torsion-free but \(\mathbb{Z}/2\mathbb{Z}\) is not.
\end{proof}
\begin{remark}
Torsion-free does not mean free abelian. For example, \(\mathbb{Q}\) is not free abelian: if it had a basis, a basis element would have to be twice another element, contrary to uniqueness of its integer coordinates in that basis.
\end{remark}
""")

add('group','free group','free-group','20E05',[],['free basis of a group'],
    'group free-algebra group-presentation cyclically-reduced',r"""
\begin{definition}
A \emph{free group on a set} \(X\) is a group \(F(X)\) with a map \(j:X\to F(X)\) such that, for every group \(H\) and map \(f:X\to H\), there is a unique homomorphism \(\overline f:F(X)\to H\) satisfying \(\overline f\circ j=f\). The image \(j(X)\) is called a \emph{free basis of a group}.
\end{definition}
\section*{Concrete construction}
Use finite words in the symbols \(x,x^{-1}\) for \(x\in X\), modulo insertion or deletion of adjacent inverse pairs. Multiplication concatenates words, the empty word is the identity, and inversion reverses a word and inverts its letters. Concatenation respects this equivalence and is associative, so the quotient is a group. Each class has a unique reduced word, obtained by cancelling adjacent inverse pairs.
\begin{proposition}
The word construction has the stated universal property.
\end{proposition}
\begin{proof}
Evaluate a word by replacing \(x\) with \(f(x)\) and \(x^{-1}\) with \(f(x)^{-1}\). Inserting or deleting an inverse pair does not change its value. Evaluation therefore descends to a homomorphism, and its values on the generators force uniqueness.
\end{proof}
\begin{example}
The free group on the empty set is trivial, and on one generator it is infinite cyclic. On two distinct generators \(a,b\), the reduced words \(ab\) and \(ba\) differ, so this free group is nonabelian.
\end{example}
This is the group-theoretic instance of a [[free-algebra|free algebra]]. Relations are imposed through a [[group-presentation|group presentation]].
""")

add('group','group presentation','group-presentation','20F05',['presentation of a group'],
    ['finitely presented group','normal closure in a group'], 'free-group group cyclically-reduced',r"""
\begin{definition}
For a set \(X\) and a set of words \(\mathcal R\subseteq F(X)\) in the [[free-group|free group]], the presentation
\[
\langle X\mid\mathcal R\rangle=F(X)/\langle\langle\mathcal R\rangle\rangle
\]
defines a group. Here the \emph{normal closure in a group} of a subset is the smallest normal subgroup containing it; it is generated by all conjugates of that subset and its inverses. Words in \(\mathcal R\) are called relators and are set equal to the identity. A group is \emph{finitely presented} if it has a presentation with both \(X\) and \(\mathcal R\) finite.
\end{definition}
\begin{proposition}
A function from \(X\) to a group \(H\) extends to a homomorphism from the presented group exactly when every relator evaluates to \(1\) in \(H\).
\end{proposition}
\begin{proof}
The function extends uniquely to \(F(X)\). It factors through the quotient precisely when its kernel contains the normal closure of the relators. As a kernel is normal, this is equivalent to killing every relator.
\end{proof}
\begin{example}
For \(n\ge1\), \(\langle a\mid a^n\rangle\) is \(\mathbb{Z}/n\mathbb{Z}\). Also \(\langle a,b\mid aba^{-1}b^{-1}\rangle\) is \(\mathbb{Z}^2\): the relation allows every word to be written \(a^m b^n\), and the map to \((m,n)\) shows these expressions are distinct.
\end{example}
\begin{remark}
Normal closure in a group is different from normal closure of a field extension. It is also different from the normalizer of a subgroup.
\end{remark}
""")

add('group','residually finite group','residually-finite-group','20E26',[],[],
    'group group-presentation',r"""
\begin{definition}
A group \(G\) is \emph{residually finite} if, for every \(g\ne1\), there is a homomorphism \(f:G\to F\) to a finite group such that \(f(g)\ne1\). Equivalently,
\[
\bigcap_{N\trianglelefteq G, [G:N]<\infty}N=\{1\}.
\]
Indeed, the kernel of such a map is normal of finite index; conversely, a normal subgroup of finite index provides a map to its finite quotient.
\end{definition}
\begin{example}
Finite groups are residually finite, using the identity homomorphism. The infinite cyclic group \(\mathbb{Z}\) is residually finite: if \(m\ne0\), reduction modulo \(|m|+1\) does not kill \(m\).
\end{example}
\begin{proposition}
Every subgroup of a residually finite group is residually finite.
\end{proposition}
\begin{proof}
For a nonidentity element of the subgroup, restrict a separating homomorphism of the larger group to that subgroup.
\end{proof}
\begin{remark}
The additive group \(\mathbb{Q}\) is not residually finite. For a homomorphism to a finite group of order \(n\), write \(q=n(q/n)\). Its image is the \(n\)-th power of the image of \(q/n\), hence the identity by Lagrange's theorem. Thus all such homomorphisms are trivial.
\end{remark}
""")

add('group','perfect group','perfect-group','20F12',[],[],
    'commutator-subgroup solvable-group group',r"""
\begin{definition}
A group \(G\) is \emph{perfect} if \(G=[G,G]\), where \([G,G]\) is its [[commutator-subgroup|commutator subgroup]]. Equivalently, its abelianization \(G/[G,G]\) is trivial.
\end{definition}
\begin{proposition}
A group is perfect exactly when every homomorphism from it to an abelian group is trivial. A perfect solvable group is trivial.
\end{proposition}
\begin{proof}
Homomorphisms to abelian groups kill all commutators, hence kill a perfect group. Conversely, apply the stated property to the quotient map onto the abelianization. If a group is perfect, every term of its derived series equals the group; if it is also solvable, that series eventually equals \(1\).
\end{proof}
\begin{example}
The trivial group is perfect; a nontrivial abelian group is not. Every nonabelian simple group is perfect: its commutator subgroup is normal and is nontrivial because the group is nonabelian, so simplicity forces it to be the whole group.
\end{example}
\begin{remark}
The adjective perfect here concerns commutators. It has no connection with the definition of a perfect field or a perfect subset of a topological space.
\end{remark}
""")

add('group','Frattini subgroup','frattini-subgroup','20E28',[],[],
    'characteristic-subgroup group cyclic-group',r"""
\begin{definition}
The \emph{Frattini subgroup} \(\Phi(G)\) is the intersection of all maximal proper subgroups of \(G\). If there are none, the intersection is taken to be \(G\). Automorphisms permute maximal proper subgroups, so \(\Phi(G)\) is a [[characteristic-subgroup|characteristic subgroup]].
\end{definition}
\begin{proposition}
For a finite group \(G\), an element \(x\) belongs to \(\Phi(G)\) exactly when, for every subset \(S\subseteq G\), the equality \(\langle S,x\rangle=G\) implies \(\langle S\rangle=G\).
\end{proposition}
\begin{proof}
If \(x\in\Phi(G)\) and \(\langle S\rangle\) is proper, finiteness places it inside a maximal proper subgroup \(M\). Then \(x\in M\) too, so \(\langle S,x\rangle\ne G\). Conversely, if \(x\notin\Phi(G)\), some maximal proper subgroup \(M\) omits \(x\). Taking \(S=M\) gives \(\langle S,x\rangle=G\) but \(\langle S\rangle=M\ne G\).
\end{proof}
\begin{example}
For a cyclic group \(G=\langle g\rangle\) of order \(p^n\), with \(p\) prime and \(n\ge1\), its unique maximal subgroup is \(\langle g^p\rangle\). Hence \(\Phi(G)=\langle g^p\rangle\). In particular, \(\Phi(C_p)=1\).
\end{example}
""")
add('ring','polynomial ring','polynomial-ring','13B25 13F20',[],[],
    'ring formal-power-series-ring integral-domain integral-extension',r"""
\begin{definition}
For a commutative ring \(R\) with identity, the \emph{polynomial ring} \(R[x]\) consists of formal finite sums \(\sum_{i\ge0}a_ix^i\), with coefficientwise addition and multiplication
\[
\left(\sum_i a_ix^i\right)\left(\sum_j b_jx^j\right)=\sum_n\left(\sum_{i+j=n}a_ib_j\right)x^n.
\]
Only finitely many coefficients are nonzero. The symbol \(x\) is an indeterminate. Repeating this construction gives \(R[x_1,\ldots,x_n]\).
\end{definition}
\begin{proposition}
For a unital map \(f:R\to S\) of commutative rings and \(s\in S\), there is a unique unital homomorphism \(R[x]\to S\) extending \(f\) and sending \(x\) to \(s\).
\end{proposition}
\begin{proof}
Send \(\sum a_ix^i\) to \(\sum f(a_i)s^i\). The addition and multiplication formulas show this is a homomorphism. Every polynomial is built from constants and \(x\), so these prescribed values force uniqueness.
\end{proof}
\begin{example}
Over \(\mathbb{F}_2\), the nonzero polynomial \(x^2-x\) gives the zero function on \(\mathbb{F}_2\). Thus formal polynomials need not be determined by their associated functions.
\end{example}
\begin{remark}
If \(R\) is an integral domain, leading coefficients show that the product of two nonzero polynomials is nonzero, so \(R[x]\) is a domain. Unlike [[formal-power-series-ring|formal power series]], polynomials have finite support.
\end{remark}
""",('Romyar Sharifi','Abstract Algebra, Chapter 3: Rings','https://www.math.ucla.edu/~sharifi/notes/algebra-ch03.html'))

add('ring','localization of a commutative ring','localization-of-a-ring','13B30',
    ['localization of a ring','ring of fractions'],[],
    'ring multiplicatively-closed localization-of-a-module field-of-fractions local-ring',r"""
\begin{definition}
Let \(R\) be a commutative unital ring and \(S\subseteq R\) contain \(1\) and be closed under multiplication. Its \emph{localization} \(S^{-1}R\) consists of fractions \(r/s\), where
\[
r/s=r'/s'\quad\Longleftrightarrow\quad t(s'r-sr')=0\text{ for some }t\in S.
\]
Addition and multiplication are \(r/s+r'/s'=(rs'+r's)/(ss')\) and \((r/s)(r'/s')=rr'/(ss')\). The canonical map sends \(r\) to \(r/1\). Each \(s/1\), \(s\in S\), is invertible with inverse \(1/s\). If \(0\in S\), the localization is the zero ring.
\end{definition}
\begin{proposition}
If \(f:R\to T\) is a unital map to a commutative ring and every \(f(s)\) is invertible, it extends uniquely to \(S^{-1}R\to T\), by \(r/s\mapsto f(r)f(s)^{-1}\).
\end{proposition}
\begin{proof}
Applying \(f\) to the equality criterion and cancelling the units \(f(t),f(s),f(s')\) proves independence of representatives. The fraction formulas prove additivity and multiplicativity. Any extension must send an inverse of \(s/1\) to the inverse of \(f(s)\), proving uniqueness.
\end{proof}
\begin{example}
Localizing \(\mathbb{Z}\) at \(\{1,2,2^2,\ldots\}\) gives \(\mathbb{Z}[1/2]\). The canonical map need not be injective: inverting \(2\) in \(\mathbb{Z}/6\mathbb{Z}\) kills the nonzero class of \(3\).
\end{example}
""",stacks('00CM','Localization'))

add('ring','field of fractions','field-of-fractions','13B30 13G05',
    ['fraction field','quotient field'],[],
    'integral-domain localization-of-a-ring field',r"""
\begin{definition}
For an integral domain \(D\), its \emph{field of fractions} \(\operatorname{Frac}(D)\) is the [[localization-of-a-ring|localization]] at \(D\setminus\{0\}\). Its elements are fractions \(a/b\) with \(b\ne0\), and \(a/b=c/d\) exactly when \(ad=bc\).
\end{definition}
\begin{proposition}
The canonical map \(D\to\operatorname{Frac}(D)\) is injective and the localization is a field. Any embedding \(D\to K\) into a field extends uniquely to an embedding \(\operatorname{Frac}(D)\to K\).
\end{proposition}
\begin{proof}
The equality criterion gives \(a/1=0/1\) only when \(a=0\). A nonzero fraction \(a/b\) has \(a\ne0\), so its inverse is \(b/a\). An embedding \(f:D\to K\) extends by \(a/b\mapsto f(a)/f(b)\), using the localization property. If this image is zero, then \(f(a)=0\), hence \(a=0\), proving injectivity. The images of fractions also force uniqueness.
\end{proof}
\begin{example}
The fraction field of \(\mathbb{Z}\) is \(\mathbb{Q}\). For a field \(k\), that of \(k[x]\) is the rational function field \(k(x)\).
\end{example}
\begin{remark}
Inside a field containing \(D\), these fractions form the smallest subfield containing \(D\). The domain hypothesis matters: one cannot invert zero divisors while retaining an embedding of the original ring into a field.
\end{remark}
""",stacks('00CM','Localization'))

add('ring','unique factorization domain','unique-factorization-domain','13F15 13A05',
    ['UFD','factorial domain'],[],
    'integral-domain gcd-domain principal-ideal-domain',r"""
\begin{definition}
A \emph{unique factorization domain} is an integral domain \(D\) in which each nonzero nonunit is a finite product of irreducible elements, uniquely up to permutation and multiplication of factors by units. An element is irreducible if it is a nonzero nonunit and every factorization of it has a unit factor. Elements differing by a unit factor are associates.
\end{definition}
\begin{proposition}
In a UFD, every irreducible element \(p\) is prime: if \(p\mid ab\), then \(p\mid a\) or \(p\mid b\).
\end{proposition}
\begin{proof}
The cases of a zero factor or a unit factor are immediate. Otherwise, factor \(a\) and \(b\) into irreducibles. From \(ab=pc\), uniqueness of factorization implies that \(p\) is associate to a factor occurring in \(a\) or \(b\), and hence divides that element.
\end{proof}
\begin{example}
The fundamental theorem of arithmetic says that \(\mathbb{Z}\) is a UFD. Fields also satisfy the definition vacuously, since they have no nonzero nonunits.
\end{example}
\begin{remark}
Uniqueness alone is insufficient: existence of a finite factorization is part of the definition. A UFD is a [[gcd-domain|gcd domain]]: take the minimum exponent of each irreducible in the factorizations of two nonzero elements. If one element is zero, the other is a greatest common divisor.
\end{remark}
""",stacks('034O','Factorization'))

add('ring','integral extension','integral-extension','13B21',[],['integral element'],
    'ring polynomial-ring field-of-fractions',r"""
\begin{definition}
Let \(A\subseteq B\) be commutative rings with the same identity. An element \(b\in B\) is \emph{integral over} \(A\) if it satisfies a monic polynomial equation
\[
b^n+a_{n-1}b^{n-1}+\cdots+a_0=0,\qquad a_i\in A,\quad n\ge1.
\]
It is then an \emph{integral element}. The extension \(B/A\) is \emph{integral} if every element of \(B\) is integral over \(A\).
\end{definition}
\begin{proposition}
If \(b\) satisfies such an equation of degree \(n\), then the subring \(A[b]\) is generated as an \(A\)-module by \(1,b,\ldots,b^{n-1}\).
\end{proposition}
\begin{proof}
The equation expresses \(b^n\) as a combination of lower powers. Multiplying it by higher powers and inducting expresses every power of \(b\) in the same span. Every element of \(A[b]\) is a polynomial in \(b\).
\end{proof}
\begin{example}
Every \(a+b\sqrt2\), with \(a,b\in\mathbb{Z}\), satisfies \((x-a)^2-2b^2=0\). Thus \(\mathbb{Z}[\sqrt2]/\mathbb{Z}\) is integral. In contrast, \(1/2\) is not integral over \(\mathbb{Z}\): multiplying a hypothetical monic equation of degree \(n\) by \(2^n\) gives an odd integer equal to zero.
\end{example}
\begin{remark}
Over a field, being integral is equivalent to being algebraic, since a nonzero leading coefficient can be divided out. Over a general ring, the monic requirement is essential.
\end{remark}
""",stacks('00GH','Finite and integral ring extensions'))

add('ring','Noetherian module','noetherian-module','16P40 16D10',[],[],
    'module equivalent-defining-conditions-on-a-noetherian-ring',r"""
\begin{definition}
A unital left \(R\)-module \(M\) is \emph{Noetherian} if every ascending chain of submodules stabilizes: for \(M_1\subseteq M_2\subseteq\cdots\), some \(N\) satisfies \(M_n=M_N\) for all \(n\ge N\). Right Noetherian modules are defined with right submodules.
\end{definition}
\begin{proposition}
A module is Noetherian if and only if every submodule is finitely generated.
\end{proposition}
\begin{proof}
If a submodule were not finitely generated, successively choose an element outside the span of those already chosen. Their spans give a strictly ascending chain. Conversely, the union \(U\) of an ascending chain is a submodule. If \(U\) has finitely many generators, all lie in some one member \(M_N\), so \(U=M_N\) and the chain stabilizes.
\end{proof}
\begin{example}
As a \(\mathbb{Z}\)-module, \(\mathbb{Z}\) is Noetherian because each subgroup is cyclic. The direct sum \(\bigoplus_{n\ge1}\mathbb{Z}\) is not: the spans of the first \(n\) standard generators form a strictly ascending chain.
\end{example}
\begin{remark}
Submodules inherit the ascending chain condition. Quotients inherit it by taking inverse images of chains under the quotient map. A ring is left Noetherian precisely when its left regular module is Noetherian; the right-handed assertion is separate for noncommutative rings.
\end{remark}
""",stacks('00FM','Noetherian rings and modules'))

add('ring','Jacobson ring','jacobson-ring','13A15',[],[],
    'ring ideal-of-a-ring jacobson-radical local-ring',r"""
\begin{definition}
A commutative unital ring \(R\) is a \emph{Jacobson ring} if every prime ideal \(\mathfrak p\) is the intersection of the maximal ideals containing it:
\[
\mathfrak p=\bigcap_{\mathfrak m\supseteq\mathfrak p, \mathfrak m\text{ maximal}}\mathfrak m.
\]
Here prime and maximal ideals are ring-theoretic ideals as defined in [[ideal-of-a-ring|ideal of a ring]].
\end{definition}
\begin{example}
Every field is Jacobson. The ring \(\mathbb{Z}\) is Jacobson: a nonzero prime ideal is already maximal, and the intersection of all prime-generated maximal ideals is \((0)\), since a nonzero integer has only finitely many prime divisors.
\end{example}
\begin{proposition}
A local integral domain is a Jacobson ring if and only if it is a field.
\end{proposition}
\begin{proof}
In a local ring, the unique maximal ideal \(\mathfrak m\) is the intersection of all maximal ideals containing \((0)\). In a domain \((0)\) is prime, so the Jacobson condition forces \(\mathfrak m=(0)\). Every nonunit belongs to a maximal ideal; thus every nonzero element is a unit. Conversely, a field is Jacobson.
\end{proof}
\begin{remark}
For example, the localization \(\mathbb{Z}_{(p)}\), consisting of rational numbers with denominator not divisible by a fixed prime \(p\), is a local domain and not a field, so it is not Jacobson. The Jacobson ring property is different from merely having zero Jacobson radical.
\end{remark}
""",stacks('00G0','Jacobson rings'))

add('ring','primary ideal','primary-ideal','13A15',[],[],
    'ideal-of-a-ring radical-of-an-ideal primary-decomposition-theorem1',r"""
\begin{definition}
An ideal \(Q\ne R\) of a commutative unital ring \(R\) is \emph{primary} if \(ab\in Q\) and \(a\notin Q\) imply \(b^n\in Q\) for some \(n\ge1\). Equivalently, every zero divisor in \(R/Q\) is nilpotent: a nonzero annihilating factor witnesses the stated implication. We include zero among zero divisors for this equivalence.
\end{definition}
\begin{proposition}
The radical \(\sqrt Q\) of a primary ideal is prime.
\end{proposition}
\begin{proof}
It is proper because \(1\notin\sqrt Q\). If \(ab\in\sqrt Q\), then \(a^m b^m\in Q\) for some \(m\ge1\). If \(a\notin\sqrt Q\), then \(a^m\notin Q\), so primaryness gives \((b^m)^n\in Q\) for some \(n\ge1\). Thus \(b\in\sqrt Q\).
\end{proof}
\begin{example}
For a prime integer \(p\) and \(k\ge1\), the ideal \((p^k)\) in \(\mathbb{Z}\) is primary: if \(p^k\mid ab\) but \(p^k\nmid a\), then \(p\mid b\), so \(p^k\mid b^k\). Its radical is \((p)\). For \(k>1\) it is not prime. The ideal \((6)\) is not primary, since \(2\cdot3\in(6)\) but neither \(2\) nor any power of \(3\) belongs to \((6)\).
\end{example}
Primary ideals are the components studied in [[primary-decomposition-theorem1|primary decomposition]].
""",('Romyar Sharifi','Abstract Algebra, Chapter 11: Commutative algebra','https://www.math.ucla.edu/~sharifi/notes/algebra-ch11.html'))
add('set','transitive set','transitive-set','03E20 03E30',[],[],
    'properties-of-ordinals transitive-closure-of-a-set cumulative-hierarchy',r"""
\begin{definition}
A set \(T\) is \emph{transitive} if every element of \(T\) is a subset of \(T\). Equivalently,
\[
x\in y\in T\Longrightarrow x\in T,\qquad\text{or}\qquad\bigcup T\subseteq T.
\]
This is a condition on membership in a set, distinct from transitivity of an arbitrary binary relation.
\end{definition}
\begin{example}
The sets \(\varnothing\), \(\{\varnothing\}\), and \(\{\varnothing,\{\varnothing\}\}\) are transitive. The set \(\{\{\varnothing\}\}\) is not: its element contains \(\varnothing\), but \(\varnothing\) is not an element of the outer set. Every ordinal is transitive by its definition.
\end{example}
\begin{proposition}
The union of any set of transitive sets is transitive. A nonempty intersection of transitive sets is transitive.
\end{proposition}
\begin{proof}
If \(x\in y\in\bigcup\mathcal T\), choose \(T\in\mathcal T\) with \(y\in T\); transitivity gives \(x\in T\subseteq\bigcup\mathcal T\). If \(y\) belongs to every \(T\in\mathcal T\), then each \(x\in y\) also belongs to every \(T\), proving the intersection assertion.
\end{proof}
\begin{remark}
Not every transitive set is an ordinal. For instance \(\{\varnothing,\{\varnothing\},\{\{\varnothing\}\}\}\) is transitive, but its membership relation is not transitive, and so is not a strict well-order.
\end{remark}
""")

add('set','transitive closure of a set','transitive-closure-of-a-set','03E20 03E30',[],[],
    'transitive-set hereditarily-finite-set closure-of-a-relation-with-respect-to-a-property',r"""
\begin{definition}
The \emph{transitive closure of a set} \(A\), denoted \(\operatorname{TC}(A)\), is the least transitive set containing \(A\) as a subset. Explicitly, put
\[
U_0=A,\qquad U_{n+1}=\bigcup U_n,\qquad \operatorname{TC}(A)=\bigcup_{n<\omega}U_n.
\]
The indexing set \(\omega\) consists of the nonnegative integers.
\end{definition}
\begin{proposition}
This formula gives a transitive set containing \(A\), and it is contained in every transitive set containing \(A\).
\end{proposition}
\begin{proof}
The \(n=0\) term gives \(A\subseteq\operatorname{TC}(A)\). If \(y\in U_n\) and \(x\in y\), then \(x\in U_{n+1}\), proving transitivity. If \(A\subseteq T\) and \(T\) is transitive, induction gives \(U_n\subseteq T\) for every \(n\), and hence the required minimality.
\end{proof}
\begin{example}
For \(A=\{\{\varnothing\}\}\), the transitive closure is \(\{\varnothing,\{\varnothing\}\}\). For a transitive set \(T\), minimality gives \(\operatorname{TC}(T)=T\).
\end{example}
\begin{remark}
Containing \(A\) as a subset is different from containing it as an element. The least transitive set having \(A\) as an element is \(\operatorname{TC}(\{A\})\). This convention also distinguishes the present construction from the [[closure-of-a-relation-with-respect-to-a-property|transitive closure of a relation]].
\end{remark}
""")

add('set','cumulative hierarchy','cumulative-hierarchy','03E30',
    ['von Neumann hierarchy'],[],
    'transitive-set transfinite-recursion properties-of-ranks-of-sets hereditarily-finite-set',r"""
\begin{definition}
The \emph{cumulative hierarchy} is the ordinal-indexed family \(V_\alpha\) given by [[transfinite-recursion|transfinite recursion]]:
\[
V_0=\varnothing,\qquad V_{\alpha+1}=\mathcal P(V_\alpha),\qquad V_\lambda=\bigcup_{\alpha<\lambda}V_\alpha\quad(\lambda\text{ a nonzero limit ordinal}).
\]
Here \(\mathcal P(X)\) denotes the set of all subsets of \(X\).
\end{definition}
\begin{proposition}
Each \(V_\alpha\) is transitive, and \(V_\alpha\subseteq V_\beta\) whenever \(\alpha\le\beta\).
\end{proposition}
\begin{proof}
The empty stage is transitive. If \(T\) is transitive, then \(T\subseteq\mathcal P(T)\). Moreover, if \(x\in y\in\mathcal P(T)\), then \(x\in T\), so \(x\subseteq T\) and \(x\in\mathcal P(T)\). Thus the successor stage is transitive and contains its predecessor. At a limit stage, the union of the preceding transitive sets is transitive and contains every earlier stage. Transfinite induction proves both assertions.
\end{proof}
\begin{example}
The first three stages are \(V_0=\varnothing\), \(V_1=\{\varnothing\}\), and \(V_2=\{\varnothing,\{\varnothing\}\}\). The set \(V_\omega\) consists of the hereditarily finite sets.
\end{example}
\begin{remark}
In ZF with Foundation, every set belongs to some stage; this is the rank theorem discussed in [[properties-of-ranks-of-sets|properties of ranks of sets]]. The union over all ordinal stages is the proper class of all sets, not another set-sized stage.
\end{remark}
""")

add('set','hereditarily finite set','hereditarily-finite-set','03E30',[],[],
    'transitive-closure-of-a-set cumulative-hierarchy properties-of-ranks-of-sets',r"""
\begin{definition}
In ZF, a set \(x\) is \emph{hereditarily finite} if \(\operatorname{TC}(\{x\})\) is finite, using the [[transitive-closure-of-a-set|transitive closure of a set]]. Thus \(x\), its elements, their elements, and so on collectively form a finite set. Equivalently, these are precisely the elements of \(V_\omega\).
\end{definition}
\begin{proof}
Every finite stage \(V_n\) is finite by induction, since the power set of a finite set is finite. If \(x\in V_n\), transitivity of \(V_n\) gives \(\operatorname{TC}(\{x\})\subseteq V_n\), so this closure is finite. Conversely, membership on a finite transitive closure is a finite acyclic relation by Foundation. Its elements have finite heights, assigning height zero to the empty set and one more than the greatest height of a member otherwise. Induction on height places every element, including \(x\), in a finite stage of the hierarchy.
\end{proof}
\begin{example}
Each natural number, represented as a finite ordinal, is hereditarily finite. So is \(\{\{\varnothing\}\}\). The singleton \(\{\omega\}\) is finite but not hereditarily finite, since its transitive closure contains all natural numbers.
\end{example}
\begin{remark}
The collection of hereditarily finite sets is a set, \(V_\omega\), not a proper class. It provides a setting for encoding finite combinatorial objects using sets alone.
\end{remark}
""")

add('set','successor cardinal','successor-cardinal','03E10',[],['limit cardinal'],
    'hartogs-number cofinality-of-an-ordinal strong-limit-cardinal inaccessible-cardinal',r"""
Work in ZFC and identify cardinals with initial ordinals.
\begin{definition}
For a cardinal \(\kappa\), the \emph{successor cardinal} \(\kappa^+\) is the least cardinal strictly greater than \(\kappa\). An infinite cardinal that is not a successor cardinal is a \emph{limit cardinal}; this convention includes \(\aleph_0\).
\end{definition}
\begin{example}
The successor of \(\aleph_n\) is \(\aleph_{n+1}\), whereas \(\aleph_\omega=\sup_{n<\omega}\aleph_n\) is a limit cardinal. Cardinal successor is different from ordinal successor: for infinite \(\kappa\), the ordinal \(\kappa+1\) still has cardinality \(\kappa\).
\end{example}
\begin{proposition}
The successor cardinal \(\kappa^+\) equals the Hartogs number of \(\kappa\).
\end{proposition}
\begin{proof}
The [[hartogs-number|Hartogs number]] is the least ordinal not admitting an injection into \(\kappa\), and is a cardinal. Every smaller or equal cardinal embeds into \(\kappa\). Conversely, no larger cardinal can embed into it. Thus the least excluded ordinal cardinal is exactly the next cardinal.
\end{proof}
\begin{remark}
The notation \(\kappa^+\) here always means cardinal successor. Some ordinal-theory texts use the same superscript for \(\alpha\cup\{\alpha\}\); interpreting the surrounding convention is essential.
\end{remark}
""")

add('set','strong limit cardinal','strong-limit-cardinal','03E10',[],[],
    'successor-cardinal inaccessible-cardinal cofinality-of-an-ordinal',r"""
Work in ZFC. For a cardinal \(\lambda\), write \(2^\lambda\) for the cardinality of its power set.
\begin{definition}
An infinite cardinal \(\kappa\) is a \emph{strong limit cardinal} if \(2^\lambda<\kappa\) for every cardinal \(\lambda<\kappa\).
\end{definition}
\begin{proposition}
Every strong limit cardinal is a limit cardinal.
\end{proposition}
\begin{proof}
If \(\kappa=\mu^+\), Cantor's theorem gives \(2^\mu>\mu\), hence \(2^\mu\ge\mu^+=\kappa\), contradicting the defining condition. Thus \(\kappa\) is not a successor cardinal.
\end{proof}
\begin{example}
The cardinal \(\aleph_0\) is strong limit because finite sets have finite power sets. A larger example is \(\beth_\omega\), defined by \(\beth_0=\aleph_0\), \(\beth_{n+1}=2^{\beth_n}\), and \(\beth_\omega=\sup_{n<\omega}\beth_n\). If \(\lambda<\beth_\omega\), some \(n\) satisfies \(\lambda\le\beth_n\), so \(2^\lambda\le\beth_{n+1}<\beth_\omega\).
\end{example}
\begin{remark}
A strong limit cardinal need not be regular: the strictly increasing countable sequence just displayed is cofinal in \(\beth_\omega\), so its cofinality is \(\omega\), smaller than \(\beth_\omega\). Uncountable regular strong limits are the strongly inaccessible cardinals.
\end{remark}
""")

add('set','inaccessible cardinal','inaccessible-cardinal','03E55',
    ['strongly inaccessible cardinal'],['weakly inaccessible cardinal'],
    'strong-limit-cardinal successor-cardinal cofinality-of-an-ordinal cumulative-hierarchy',r"""
Work in ZFC and use the strong convention for the unqualified term inaccessible.
\begin{definition}
An \emph{inaccessible cardinal} is an uncountable cardinal \(\kappa\) that is regular and strong limit:
\[
\operatorname{cf}(\kappa)=\kappa,\qquad 2^\lambda<\kappa\quad\text{for all cardinals }\lambda<\kappa.
\]
A \emph{weakly inaccessible cardinal} is an uncountable regular limit cardinal. Regularity is as defined in [[cofinality-of-an-ordinal|cofinality of an ordinal]].
\end{definition}
\begin{proposition}
If \(\kappa\) is inaccessible and \((X_i)_{i\in I}\) is a family with \(|I|<\kappa\) and \(|X_i|<\kappa\) for every \(i\), then \(\left|\bigcup_{i\in I}X_i\right|<\kappa\). Also \(|\mathcal P(X)|<\kappa\) whenever \(|X|<\kappa\).
\end{proposition}
\begin{proof}
Regularity bounds the fewer than \(\kappa\) cardinals \(|X_i|\) by a common cardinal below \(\kappa\). Increase that bound to an infinite cardinal \(\mu<\kappa\) also bounding \(|I|\). By choice, the union has cardinality at most \(\mu\cdot\mu=\mu<\kappa\). The power-set assertion is precisely the strong limit condition.
\end{proof}
\begin{remark}
Every inaccessible cardinal is weakly inaccessible because a strong limit is a limit cardinal. The example \(\beth_\omega\) in [[strong-limit-cardinal|strong limit cardinal]] shows why regularity cannot be omitted. No existence assertion is part of the definition: existence of inaccessible cardinals is an additional large-cardinal hypothesis.
\end{remark}
""")

add('set','almost disjoint family','almost-disjoint-family','03E05 03E17',[],
    ['maximal almost disjoint family'], 'hausdorffs-maximum-principle',r"""
\begin{definition}
An \emph{almost disjoint family} on \(\omega\) is a collection \(\mathcal A\) of infinite subsets of \(\omega\) such that \(A\cap B\) is finite whenever \(A,B\in\mathcal A\) are distinct. A \emph{maximal almost disjoint family} is one that cannot be enlarged while retaining this property. In the usual cardinal-invariant convention, a MAD family is additionally required to be infinite; we adopt that convention here.
\end{definition}
\begin{example}
An infinite partition of \(\omega\) into infinite pieces is almost disjoint but not maximal: choosing one point from each piece produces an infinite set meeting each piece in only one point.
\end{example}
\begin{proposition}
No countably infinite almost disjoint family is maximal.
\end{proposition}
\begin{proof}
List its distinct members as \(A_0,A_1,\ldots\). Choose \(x_n\in A_n\setminus\bigcup_{i<n}A_i\), also avoiding the finitely many previously chosen points. This is possible because only finitely many finite intersections are removed from the infinite set \(A_n\). The set \(X=\{x_n:n<\omega\}\) is infinite. For fixed \(i\), no \(x_n\) with \(n>i\) belongs to \(A_i\), so \(X\cap A_i\) is finite. Thus adjoining \(X\) enlarges the family.
\end{proof}
\begin{remark}
In ZFC, Zorn's lemma extends any infinite almost disjoint family to a maximal one: the union of a chain of extensions is again almost disjoint. Combined with the proposition, this shows every MAD family is uncountable. Finite maximal families, such as \(\{\omega\}\), are excluded by the MAD convention used above.
\end{remark}
""",AD_REF)


INTRODUCTIONS = {
    'nilpotent-group': 'Nilpotence measures how many successive commutator steps are needed to reach the trivial subgroup.',
    'torsion-group': 'A group can be infinite even though each of its elements has finite order.',
    'torsion-free-group': 'Torsion-free groups have no nontrivial elements of finite order.',
    'free-group': 'A free group allows its generators to be assigned arbitrary values in any target group.',
    'group-presentation': 'Generators and relations describe a group as a quotient of a free group.',
    'residually-finite-group': 'Residual finiteness means that finite quotients can detect every nonidentity element.',
    'perfect-group': 'Perfect groups have no nontrivial abelian quotient.',
    'frattini-subgroup': 'The Frattini subgroup records elements that can be discarded from generating sets in a finite group.',
    'polynomial-ring': 'Polynomial rings turn formal expressions with coefficients into algebraic objects in their own right.',
    'localization-of-a-ring': 'Localization makes a prescribed collection of ring elements invertible.',
    'field-of-fractions': 'Every integral domain embeds in a field obtained by adjoining fractions of its elements.',
    'unique-factorization-domain': 'Unique factorization extends the familiar prime factorization of integers to integral domains.',
    'integral-extension': 'Integral dependence generalizes algebraic dependence over fields while retaining a monic equation.',
    'noetherian-module': 'The Noetherian condition prevents submodules from growing through an endless strictly ascending chain.',
    'jacobson-ring': 'In a Jacobson ring, prime ideals can be recovered from the maximal ideals above them.',
    'primary-ideal': 'Primary ideals generalize prime-power ideals in the integers.',
    'transitive-set': 'A transitive set contains every member of each of its elements.',
    'transitive-closure-of-a-set': 'Transitive closure collects the sets reached by following membership downward through finitely many steps.',
    'cumulative-hierarchy': 'The cumulative hierarchy organizes sets by repeatedly forming power sets and taking unions.',
    'hereditarily-finite-set': 'Hereditary finiteness requires finiteness throughout the membership structure of a set.',
    'successor-cardinal': 'Cardinal successor selects the next possible size of a well-orderable set.',
    'strong-limit-cardinal': 'Below a strong limit cardinal, taking a power set never reaches that cardinal.',
    'inaccessible-cardinal': 'Inaccessible cardinals combine regularity with closure of smaller cardinalities under power sets.',
    'almost-disjoint-family': 'Almost disjoint families allow finite overlaps between otherwise separate infinite sets.',
}
for e in ENTRIES:
    e['body'] = INTRODUCTIONS[e['slug']] + '\n\n' + e['body'].strip()

INCOMING = [
    ('free-algebra', 'free-group'),
    ('locally-finite-group', 'torsion-group'),
    ('gcd-domain', 'unique-factorization-domain'),
    ('reflective-subcategory', 'field-of-fractions'),
    ('primary-decomposition-theorem1', 'primary-ideal'),
    ('properties-of-ordinals', 'transitive-set'),
    ('properties-of-ranks-of-sets', 'cumulative-hierarchy'),
]


def prepare(c):
    """Resolve explicit links against real canonical names, including new entries."""
    names = dict(c.execute('SELECT slug,canonical_name FROM math_concepts'))
    names.update({e['slug']: e['canonical'] for e in ENTRIES})
    for e in ENTRIES:
        def link(m):
            slug, label = m.groups()
            assert slug in names, slug
            if slug not in e['related']:
                e['related'].append(slug)
            return r'\PMlinkname{' + label + '}{' + names[slug] + '}'
        e['body'] = re.sub(r'\[\[([^|\]]+)\|([^\]]+)\]\]', link, e['body'])
        for slug in e['related']:
            assert slug in names, (e['slug'], slug)


def verify(c):
    assert Counter(e['area'] for e in ENTRIES) == {'group':8, 'ring':8, 'set':8}
    for e in ENTRIES:
        d = fetch_public_math_concept_detail(c.cursor(), e['slug'])
        assert d and d['owner']=='CWoo' and d['cleaned_tex']==source(e), e['slug']
        for key in ['synonyms','definitions']:
            assert set(d[key])==set(e[key]), (e['slug'],key)
        assert set(d['types'])==set(document_types(e))
        assert {r['code'] for r in d['classifications']}==set(e['classifications'])
        html=d['display_tex']
        assert r'\PMlink' not in html and '[[' not in html
        pattern=r'\\\(.*?\\\)|\\\[.*?\\\]'
        assert re.findall(pattern,source(e),re.S)==re.findall(pattern,html,re.S), e['slug']
        for env in ['definition','proof','proposition','example','remark']:
            assert html.count('class="math-env math-env-'+env+'"')==e['body'].count(r'\begin{'+env+'}'), (e['slug'],env)
        for label,target in re.findall(r'\\PMlinkname\{([^{}]*)\}\{([^{}]*)\}', e['body']):
            row=c.execute('SELECT slug FROM math_concepts WHERE canonical_name=?',(target,)).fetchone()
            assert row and row[0] in links(html),(e['slug'],label,target)
        for target in links(html):
            assert c.execute('SELECT 1 FROM math_concepts WHERE slug=?',(target,)).fetchone(),target
        rows=c.execute('SELECT related_concept_id FROM math_related_concepts WHERE concept_id=?',(d['id'],)).fetchall()
        assert len(rows)>=len(e['related']) and all(r[0] for r in rows)
        assert any(r['slug']==e['slug'] for r in search_public_math_library(c.cursor(),e['title'])['data'])
        print('Verified',d['id'],e['area'],e['slug'])
    for origin,target in INCOMING:
        assert target in links(fetch_public_math_concept_detail(c.cursor(),origin)['display_tex']),(origin,target)
    assert c.execute('PRAGMA integrity_check').fetchone()[0]=='ok'
    assert not c.execute('PRAGMA foreign_key_check').fetchall()


def apply(path):
    if not path.is_file():
        raise FileNotFoundError(path)
    with sqlite3.connect(path) as c:
        c.row_factory=sqlite3.Row
        c.execute('PRAGMA foreign_keys=ON')
        prepare(c)
        # Preflight the entire batch, so collisions are reviewed before any write.
        for e in ENTRIES:
            if c.execute('SELECT 1 FROM math_concepts WHERE slug=?',(e['slug'],)).fetchone():
                continue
            for term in [e['title'],*e['synonyms'],*e['definitions']]:
                hits=c.execute('''SELECT title FROM math_concepts WHERE lower(title)=lower(?)
                    UNION SELECT synonym_text FROM math_synonyms WHERE lower(synonym_text)=lower(?)
                    UNION SELECT defined_term FROM math_definitions WHERE lower(defined_term)=lower(?)''',
                    (term,term,term)).fetchall()
                assert not hits,(e['slug'],term,[tuple(r) for r in hits])
            for code in e['classifications']:
                assert c.execute('SELECT 1 FROM math_classifications WHERE code=?',(code,)).fetchone(),code
        for e in ENTRIES:
            if not c.execute('SELECT 1 FROM math_concepts WHERE slug=?',(e['slug'],)).fetchone():
                create_math_concept(c.cursor(),e['canonical'],e['slug'],e['title'],
                    datetime.now().strftime('%Y-%m-%d %H:%M:%S'),'CWoo',source(e),1,
                    e['classifications'],document_types(e),e['synonyms'],e['definitions'],[])
        for e in ENTRIES:
            for target in e['related']:
                relate(c,e['slug'],target)
        for origin,target in INCOMING:
            relate(c,origin,target)
        verify(c)


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--db',type=Path,default=SRC.parent/'portfolio.db')
    apply(parser.parse_args().db)
