"""Ring ideals, nilpotence, two proved results and Jacobson's open conjecture.

Reviewed titles, synonyms, defined terms and full sources. Bare 'ideal' already
denotes lattice ideals, so ring ideals receive qualified names and explicit
links. Correct the upper-nilradical entry's unrestricted-summand error.
Open-problem status searched 2026-09-23; do not call Koethe open in view of the
September 2026 counterexample preprint (arXiv:2609.15080).
"""
import argparse
from datetime import datetime
from pathlib import Path
import re
import sqlite3
import sys
SRC=Path(__file__).resolve().parents[3]
sys.path.insert(0,str(SRC))
from services.math.concept_create_service import create_math_concept
from services.math.concept_render_service import render_tex_reusing_existing_diagrams
from services.math.public_concept_detail_service import fetch_public_math_concept_detail
from services.math.public_search_service import search_public_math_library
from add_eight_algebra_concepts import source, Links
from add_sylow_theorems import document_types
from add_twenty_concepts_20260922 import ESCAPES
from add_category_foundations import relate, links

REF=('Romyar Sharifi','Abstract Algebra, Chapter 8: Topics in ring theory',
     'https://www.math.ucla.edu/~sharifi/notes/algebra-ch08.html')


def entry(title,slug,canonical,codes,aliases,definitions,related,body,reference=REF):
    return dict(title=title,slug=slug,canonical=canonical,classifications=codes,
                synonyms=aliases,definitions=definitions,related=related,body=body,reference=reference,
                escapes=list(ESCAPES)+['ideal','ideals','left','right','identity','unit','normal',
                    'power','index','order','zero','finite','sum','product','radical','nilpotent',
                    'nil','commutative','generated','bound','uniform','monomial','characteristic',
                    'simple','closed','proper','maximal','minimal','local','field','inverse',
                    'positive','negative','side','fixed','term','leading','constant','instance',
                    'theory','eventually','length','spanned by','square','nor','ideal generated by','open'])


ENTRIES=[
entry('ideal of a ring','ideal-of-a-ring','IdealOfARing',['16D25','13A15'],
      ['ring ideal','ring ideals','ideals of a ring'],
      ['two-sided ideal','sum of ideals','product of ideals','power of an ideal','quotient ring'],
      ['ring','artinian-ring','radical-of-an-ideal','nil-and-nilpotent-ideals','jacobson-radical'],r"""
Ring ideals are additive subgroups closed under multiplication by ambient ring elements. They are distinct from ideals of ordered sets or lattices.
\begin{definition}
Let \(R\) be an associative ring, not necessarily commutative or unital. A left ideal is an additive subgroup \(I\) such that \(ri\in I\) for all \(r\in R,i\in I\); a right ideal requires \(ir\in I\). A \emph{two-sided ideal}, or \emph{ideal of a ring}, satisfies both conditions. Unless a side is specified, ideal means two-sided in this entry. The zero subgroup and \(R\) itself are ideals; an ideal is proper when it is not \(R\).

For two-sided ideals \(I,J\), their \emph{sum of ideals} is \(I+J=\{i+j:i\in I,j\in J\}\). The sum of any family consists of finite sums of elements taken from members of that family. Their \emph{product of ideals} \(IJ\) consists of finite sums of products \(ij\). The \emph{power of an ideal} \(I^n\), for \(n\ge1\), consists of finite sums of products of \(n\) elements of \(I\). These sets are two-sided ideals: addition and additive inverses are preserved, and multiplication by \(R\) is absorbed into the first or last factor. Associativity gives \(I^{m+n}=I^mI^n\).

The \emph{quotient ring} \(R/I\) has additive cosets as elements, with \((r+I)(s+I)=rs+I\).
\end{definition}
\begin{proposition}
The quotient multiplication is well-defined for a two-sided ideal. If \(R\) has identity, an ideal containing \(1\) equals \(R\).
\end{proposition}
\begin{proof}
Replacing \(r,s\) by \(r+i,s+j\) changes their product by \(rj+is+ij\in I\); thus the product coset is independent of representatives. Addition is already well-defined in the quotient additive group, and the ring laws descend from \(R\). If \(1\in I\), then every \(r=r1\) lies in \(I\).
\end{proof}
\begin{example}
The subgroup \(n\mathbb{Z}\) is an ideal of \(\mathbb{Z}\), giving the quotient \(\mathbb{Z}/n\mathbb{Z}\). In \(M_2(k)\), the matrices with zero second column form a left ideal. It is not a right ideal: the matrix unit \(E_{11}\) belongs to it but \(E_{11}E_{12}=E_{12}\) does not. Here \(E_{ij}\) has a single \(1\) in position \((i,j)\).
\end{example}
\begin{remark}
Left and right ideals were already defined in the \PMlinkname{Artinian ring}{ArtinianRing} entry. This entry collects the general ring-theoretic definitions without changing the existing meaning of the bare search term ``ideal'' in lattice theory.
\end{remark}
""",('Romyar Sharifi','Abstract Algebra, Chapter 3: Ring theory','https://www.math.ucla.edu/~sharifi/notes/algebra-ch03.html')),
entry('nilpotent element','nilpotent-element','NilpotentElement',['16N40'],
      ['nilpotent elements','nilpotence in rings'],['nilpotency index of an element'],
      ['ring','matrix-ring','reduced-ring','topologically-nilpotent','nil-and-nilpotent-ideals'],r"""
Nilpotence means that repeated multiplication eventually gives exactly zero.
\begin{definition}
An element \(a\) of an associative ring is a \emph{nilpotent element} if \(a^n=0\) for some integer \(n\ge1\). The least such \(n\) is its \emph{nilpotency index}. In particular, zero has index one. No multiplicative identity is required for this definition.
\end{definition}
\begin{example}
In \(\mathbb{Z}/8\mathbb{Z}\), the class of \(2\) has index three. In \(M_2(k)\), \(E_{12}^2=E_{21}^2=0\), while \((E_{12}+E_{21})^2=1\). Thus a sum of nilpotent elements need not be nilpotent in a noncommutative ring. This example works over any field.
\end{example}
\begin{proposition}
In a unital ring, if \(a^n=0\), then \(1-a\) is invertible, with inverse \(1+a+\cdots+a^{n-1}\).
\end{proposition}
\begin{proof}
Multiplying the displayed sum on either side by \(1-a\) telescopes to \(1-a^n=1\). Only powers of the same element are involved, so commutativity of the whole ring is unnecessary.
\end{proof}
\begin{remark}
An algebraically nilpotent element is \PMlinkname{topologically nilpotent}{TopologicallyNilpotent} in any normed ring, since its sufficiently high powers vanish. The converse need not hold; algebraic nilpotence is an exact finite-power condition. This is also different from nilpotence of a group.
\end{remark}
"""),
entry('nil and nilpotent ideals','nil-and-nilpotent-ideals','NilAndNilpotentIdeals',['16N40'],[],
      ['nil ideal','nilpotent ideal','nil ring','nilpotent ring'],
      ['ideal-of-a-ring','nilpotent-element','upper-nilradical','sums-of-nil-ideals','finitely-generated-nil-ideals-are-nilpotent'],r"""
For a nil ideal the vanishing exponent may depend on the element. Nilpotence of an ideal requires a single exponent controlling all products of that length.
\begin{definition}
A left, right or two-sided ideal \(I\) is a \emph{nil ideal} if every \(a\in I\) is nilpotent. It is a \emph{nilpotent ideal} if \(I^N=0\) for some \(N\ge1\), meaning every product of \(N\) possibly different elements of \(I\) is zero. Ideal powers are as in \PMlinkname{ideal of a ring}{IdealOfARing}. A \emph{nil ring} is a ring all of whose elements are nilpotent; a \emph{nilpotent ring} satisfies \(R^N=0\) for some \(N\). Nonzero nil rings cannot have a multiplicative identity, since no power of \(1\) is zero.
\end{definition}
Every nilpotent ideal is nil: taking the same element in all \(N\) factors gives \(a^N=0\). The converse fails, even for two-sided ideals in a commutative unital ring.
\begin{example}
Let \(k\) be a field and let
\[
R=k[x_1,x_2,\ldots]/(x_1^2,x_2^2,\ldots),\qquad I=(\overline{x}_1,\overline{x}_2,\ldots).
\]
An element of \(I\) involves only finitely many variables, say \(d\) of them, and has no constant term. In its \((d+1)\)-st power, each monomial repeats a variable, so vanishes. Thus \(I\) is nil. But \(\overline{x}_1\cdots\overline{x}_N\in I^N\) is nonzero for every \(N\): the ideal of relations is spanned by monomials containing a square, and a product of distinct variables is not one of them. Hence \(I\) is not nilpotent.
\end{example}
\begin{remark}
This example also distinguishes finite generation of an ideal from allowing infinitely many generators. In the commutative case, finitely many nilpotent ideal generators do imply a nilpotent ideal, as proved in \PMlinkname{the finite-generation theorem}{FinitelyGeneratedNilIdealsAreNilpotent}. In noncommutative rings, do not replace products of different elements by powers of one element without justification.
\end{remark}
"""),
entry('sums of nil ideals','sums-of-nil-ideals','SumsOfNilIdeals',['16N40'],
      ['sum of nil two-sided ideals'],[],
      ['ideal-of-a-ring','nil-and-nilpotent-ideals','nilpotent-element','upper-nilradical'],r"""
The sum of nil two-sided ideals is nil, even without commutativity or a multiplicative identity.
\begin{theorem}
If \(I,J\) are nil two-sided ideals of an associative ring \(R\), then \(I+J\) is nil. More generally, a sum of any family of nil two-sided ideals is nil.
\end{theorem}
\begin{proof}
Take \(x=i+j\), with \(i\in I\) and \(j\in J\). Choose \(m\ge1\) with \(i^m=0\). In the quotient ring \(R/J\), the coset of \(x\) equals that of \(i\), so \(x^m\in J\). Since \(J\) is nil, \((x^m)^n=0\) for some \(n\ge1\). Thus \(x\) is nilpotent. Induction handles finite sums of ideals. Every element of an arbitrary ideal sum belongs to such a finite sum, proving the general assertion.
\end{proof}
\begin{corollary}
The sum of all nil two-sided ideals is the largest nil two-sided ideal of \(R\), its \PMlinkname{upper nilradical}{UpperNilradical}.
\end{corollary}
\begin{proof}
The sum is a two-sided ideal and is nil by the theorem. It contains every nil two-sided ideal by construction.
\end{proof}
\begin{remark}
The quotient argument requires \(J\) to be two-sided. It does not prove the corresponding assertion for nil one-sided ideals. Nor does the theorem say that arbitrary sums of nilpotent elements are nilpotent: the matrix example in \PMlinkname{nilpotent element}{NilpotentElement} disproves that assertion.
\end{remark}
"""),
entry('finitely generated nil ideals in commutative rings are nilpotent','finitely-generated-nil-ideals-are-nilpotent','FinitelyGeneratedNilIdealsAreNilpotent',
      ['13A15','13E05'],['nilpotence of finitely generated nil ideals in commutative rings'],[],
      ['ideal-of-a-ring','nil-and-nilpotent-ideals','nilpotent-element','equivalent-defining-conditions-on-a-noetherian-ring','upper-nilradical'],r"""
In commutative rings, finitely many nilpotent generators give an explicit bound for the power that kills their ideal. Throughout this entry, \(R\) is commutative and unital.
\begin{theorem}
Let \(I=(a_1,\ldots,a_r)\) with \(r\ge1\) and \(a_i^{n_i}=0\), where \(n_i\ge1\). Then
\[
I^N=0,\qquad N=1+\sum_{i=1}^{r}(n_i-1).
\]
In particular, every finitely generated nil ideal of \(R\) is nilpotent.
\end{theorem}
\begin{proof}
Here \(I=(a_1,\ldots,a_r)\) means its elements are sums \(\sum_i c_i a_i\) with \(c_i\in R\). Expanding a product of \(N\) such elements and using commutativity, each summand is a coefficient times \(a_1^{e_1}\cdots a_r^{e_r}\), with \(\sum_i e_i=N\). If every \(e_i<n_i\), their sum is at most \(\sum_i(n_i-1)=N-1\), a contradiction. Thus a factor \(a_i^{n_i}\) occurs and the summand is zero. The zero ideal is already nilpotent, including when it is viewed as generated by the empty set.
\end{proof}
\begin{corollary}
Every nil ideal of a commutative Noetherian ring is nilpotent. In particular, its nilradical is nilpotent.
\end{corollary}
\begin{proof}
The \PMlinkname{Noetherian condition}{EquivalentDefiningConditionsOnANoetherianRing} makes every ideal finitely generated, so the theorem applies to a nil ideal. In a commutative ring the nilpotent elements themselves form an ideal: if \(a^m=b^n=0\), the binomial expansion gives \((a+b)^{m+n-1}=0\), and \((ra)^m=r^ma^m=0\); additive inverses are nilpotent too. This ideal is the nilradical and hence is nil, so the first assertion applies to it.
\end{proof}
\begin{example}
In \(k[x,y]/(x^3,y^4)\), the ideal generated by the images of \(x,y\) satisfies \(I^6=0\). The product \(\overline{x}^2\overline{y}^3\) is nonzero, since it is not divisible by either defining monomial, so \(I^5\ne0\). The bound is attained.
\end{example}
\begin{remark}
Commutativity is used to collect equal generators together. Nil ideals with infinitely many generators need not be nilpotent.
\end{remark}
""",('The Stacks Project','Locally nilpotent ideals, Section 10.32','https://stacks.math.columbia.edu/tag/00IM')),
entry("Jacobson's conjecture",'jacobsons-conjecture','JacobsonsConjecture',['16N20','16P40'],
      ['Jacobson conjecture','Jacobson radical intersection conjecture'],[],
      ['jacobson-radical','ideal-of-a-ring','equivalent-defining-conditions-on-a-noetherian-ring','nil-and-nilpotent-ideals','finitely-generated-nil-ideals-are-nilpotent'],r"""
This open problem asks whether powers of the Jacobson radical of a two-sided Noetherian ring can have a nonzero common element.
\begin{conjecture}
Let \(R\) be an associative unital ring that is both left Noetherian and right Noetherian. If \(J(R)\) is its Jacobson radical, then
\[
\bigcap_{n=1}^{\infty}J(R)^n=0.
\]
\end{conjecture}
The \PMlinkname{Noetherian hypotheses}{EquivalentDefiningConditionsOnANoetherianRing} mean ascending chains stabilize separately for left and right ideals. The \PMlinkname{Jacobson radical}{JacobsonRadical} is the intersection of the maximal left ideals (equivalently maximal right ideals); \(J(R)^n\) is an ideal power, not the set of individual \(n\)-th powers.

Status reviewed on 2026-09-23: the general left-and-right Noetherian problem remains listed as open in the research literature reviewed for this entry; no established general resolution was located in the accompanying current literature search. The reference gives the two-sided formulation and known special cases. This statement should be revisited if new research appears.
\begin{proposition}
If \(J(R)\) is nilpotent, then the asserted intersection is zero.
\end{proposition}
\begin{proof}
If \(J(R)^N=0\), the intersection is contained in this zero ideal. This proves only the stated special case, not the general conjecture.
\end{proof}
\begin{example}
In \(\mathbb{Z}/8\mathbb{Z}\), the only maximal ideal is \((\overline{2})\): its quotient is the field of two elements, and every proper ideal is contained in it since every odd residue is a unit. Thus \(J(R)=(\overline{2})\) and \(J(R)^3=0\).
\end{example}
\begin{remark}
The conjecture does not assert that the Jacobson radical is nil or nilpotent, or that the descending sequence of its powers stabilizes. Ascending-chain conditions alone do not imply a descending-chain condition. Both the left and right Noetherian hypotheses belong to the formulation; one-sided variants must not be silently substituted. The proved commutative result about nil ideals applies to nil ideals, whereas a Jacobson radical need not be nil.
\end{remark}
""",('Paula Carvalho and Christian Lomp','Noetherian rings whose injective hulls of simple modules are locally Artinian (research seminar abstract)',
      'https://pnp.mathematik.uni-stuttgart.de/iaz/iaz1/Oberseminar/abstracts/CarvalhoLomp.pdf')),
entry("Köthe's conjecture",'kothes-conjecture','KothesConjecture',['16N40'],
      ["Kothe's conjecture",'Kothe conjecture',"Koethe's conjecture",'Koethe conjecture','Köthe conjecture'],[],
      ['nil-and-nilpotent-ideals','sums-of-nil-ideals','upper-nilradical','ideal-of-a-ring'],r"""
Köthe's conjecture concerns sums of nil one-sided ideals. A counterexample was reported in a preprint submitted on September 14, 2026; this entry therefore records the classical conjecture with that status update, rather than presenting it as an unqualified open problem.
\section*{Classical statement}
\begin{conjecture}
In any associative ring \(R\), the sum of two nil left ideals is nil. Explicitly, if every element of the left ideals \(I,J\) is nilpotent, then every element of \(I+J\) is nilpotent.
\end{conjecture}
The corresponding right-ideal formulation is obtained by reversing multiplication. See \PMlinkname{nil and nilpotent ideals}{NilAndNilpotentIdeals} for the distinction between elementwise nilpotence and nilpotence of an entire ideal.
\section*{September 14, 2026 counterexample preprint}
B. Greenfeld, B. King and L. Vendramin report a construction refuting the conjecture in \PMlinkexternal{The Köthe conjecture via point modules, arXiv:2609.15080v1}{https://arxiv.org/abs/2609.15080v1}, submitted September 14, 2026. Their abstract describes a construction based on point modules. Status checked September 23, 2026: this entry attributes the counterexample to that preprint; its construction and proof are not reproduced here. The reference below links to the current arXiv record for subsequent revisions.
\begin{remark}
This does not contradict the \PMlinkname{theorem on sums of nil two-sided ideals}{SumsOfNilIdeals}. Its quotient-ring proof uses two-sidedness, whereas the classical conjecture concerns one-sided ideals. Nor is an arbitrary pair of nilpotent elements, whose sum need not be nilpotent, by itself a counterexample to the ideal-theoretic assertion.
\end{remark}
""",('B. Greenfeld, B. King and L. Vendramin','The Köthe conjecture via point modules (preprint, submitted September 14, 2026)',
      'https://arxiv.org/abs/2609.15080')),
]

OLD_UPPER = r'''The \emph{upper nilradical} $\operatorname{Nil}^*(R)$ of $R$ is the \PMlinkname{sum}{SumOfIdeals} of all (two-sided) nil ideals in $R$.  In other words, $a\in Nil^* R$ iff $a$ can be expressed as a (finite) sum of nilpotent elements.'''
NEW_UPPER = r'''The \emph{upper nilradical} $\operatorname{Nil}^*(R)$ of $R$ is the \PMlinkname{sum}{IdealOfARing} of all two-sided \PMlinkname{nil ideals}{NilAndNilpotentIdeals} in $R$. Equivalently, its elements are finite sums whose summands each belong to a nil two-sided ideal. Arbitrary nilpotent elements need not qualify: they need not lie in any nil two-sided ideal. The \PMlinkname{theorem on sums of nil ideals}{SumsOfNilIdeals} proves that this sum is itself nil.'''


def types(e):
    return sorted(set(document_types(e)) | ({'Conjecture'} if r'\begin{conjecture}' in e['body'] else set()))


def verify(c):
    for e in ENTRIES:
        d=fetch_public_math_concept_detail(c.cursor(),e['slug'])
        assert d and d['owner']=='CWoo' and d['cleaned_tex']==source(e),e['slug']
        for key in ['synonyms','definitions']: assert set(d[key])==set(e[key]),(e['slug'],key)
        assert set(d['types'])==set(types(e))
        assert {r['code'] for r in d['classifications']}==set(e['classifications'])
        html=d['display_tex'];assert r'\PMlink' not in html
        assert e['slug'] not in links(html)
        for env in ['definition','proof','theorem','corollary','conjecture','example','remark','proposition']:
            assert html.count('class="math-env math-env-'+env+'"')==e['body'].count(r'\begin{'+env+'}'),(e['slug'],env)
        pattern=r'\\\(.*?\\\)|\\\[.*?\\\]'
        assert re.findall(pattern,source(e),re.S)==re.findall(pattern,html,re.S),e['slug']
        for label,target in re.findall(r'\\PMlinkname\{([^{}]*)\}\{([^{}]*)\}',e['body']):
            row=c.execute('SELECT slug FROM math_concepts WHERE canonical_name=?',(target,)).fetchone()
            assert row and row[0] in links(html),(label,target)
        assert any(r['slug']==e['slug'] for r in search_public_math_library(c.cursor(),e['title'])['data'])
        rows=c.execute('SELECT related_concept_id FROM math_related_concepts WHERE concept_id=?',(d['id'],)).fetchall()
        assert len(rows)>=len(e['related']) and all(r[0] for r in rows)
        print('Verified',d['id'],e['slug'])
    d=fetch_public_math_concept_detail(c.cursor(),'upper-nilradical')
    assert NEW_UPPER in d['cleaned_tex'] and OLD_UPPER not in d['cleaned_tex']
    assert {'ideal-of-a-ring','nil-and-nilpotent-ideals','sums-of-nil-ideals'} <= links(d['display_tex'])
    assert c.execute('PRAGMA integrity_check').fetchone()[0]=='ok'
    assert not c.execute('PRAGMA foreign_key_check').fetchall()


def apply(path):
    if not path.is_file(): raise FileNotFoundError(path)
    with sqlite3.connect(path) as c:
        c.row_factory=sqlite3.Row;c.execute('PRAGMA foreign_keys=ON')
        now=datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        for e in ENTRIES:
            if c.execute('SELECT 1 FROM math_concepts WHERE slug=?',(e['slug'],)).fetchone():continue
            for term in [e['title'],*e['synonyms'],*e['definitions']]:
                assert not c.execute('''SELECT title FROM math_concepts WHERE lower(title)=lower(?)
                    UNION SELECT synonym_text FROM math_synonyms WHERE lower(synonym_text)=lower(?)
                    UNION SELECT defined_term FROM math_definitions WHERE lower(defined_term)=lower(?)''',(term,term,term)).fetchone(),term
            for code in e['classifications']:
                assert c.execute('SELECT id FROM math_classifications WHERE code=?',(code,)).fetchone(),code
            create_math_concept(c.cursor(),e['canonical'],e['slug'],e['title'],now,'CWoo',source(e),1,e['classifications'],types(e),e['synonyms'],e['definitions'],[])
        for e in ENTRIES:
            for target in e['related']:relate(c,e['slug'],target)
        for origin in ['nil-and-nilpotent-ideals','sums-of-nil-ideals','upper-nilradical']:
            relate(c,origin,'kothes-conjecture')
        for origin,target in [('upper-nilradical','sums-of-nil-ideals'),('upper-nilradical','nil-and-nilpotent-ideals'),('artinian-ring','ideal-of-a-ring'),('jacobson-radical','jacobsons-conjecture'),('reduced-ring','nilpotent-element')]:relate(c,origin,target)
        row=c.execute("SELECT id,cleaned_tex FROM math_concepts WHERE slug='upper-nilradical'").fetchone()
        if NEW_UPPER not in row[1]:
            assert row[1].count(OLD_UPPER)==1,'Review changed upper-nilradical source before patching'
            text=row[1].replace(OLD_UPPER,NEW_UPPER)
            rendered=render_tex_reusing_existing_diagrams(row[0],text,c.cursor())
            c.execute('UPDATE math_concepts SET cleaned_tex=?,rendered_tex=?,updated_at=? WHERE id=?',(text,rendered,now,row[0]))
        verify(c)


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--db',type=Path,default=SRC.parent/'portfolio.db')
    apply(parser.parse_args().db)
