"""Eight number-theory and eight differential-geometry foundations.

Audit: searched titles, synonyms, defined terms and source text. Earlier entries
mention these notions (notably gradient and Hamilton equations), but do not give
their general definitions. Qualified aliases avoid collisions with ordinary
basis, field, ring, metric, normal, differential and discriminant terminology.
"""
import argparse
from datetime import datetime
from pathlib import Path
import re
import sqlite3
from add_group_centralizers_and_series import (
    entry, SRC, source, document_types, create_math_concept,
    fetch_public_math_concept_detail, relate, links,
)
from services.math.autolink_service import apply_math_autolinker

ANT = ('J. S. Milne', 'Algebraic Number Theory, Chapters 2-4',
       'https://www.jmilne.org/math/CourseNotes/ANT.pdf')
DG = ('Eckhard Meinrenken', 'Riemannian Geometry, Sections 1-7 and 12-16',
      'https://www.math.toronto.edu/mein/teaching/LectureNotes/rieall.pdf')
ENTRIES = []

def add(title, slug, canonical, codes, aliases, definitions, related, body, ref):
    e = entry(title, slug, canonical, codes, aliases, definitions, related, body)
    e['reference'] = ref
    e['escapes'] += ['open', 'chart', 'charts', 'normal', 'regular', 'basis',
        'metric', 'differential', 'degree', 'order', 'local', 'global', 'smooth',
        'point', 'points', 'line', 'lines', 'plane', 'coordinates', 'coordinate',
        'positive', 'negative', 'signature', 'trace', 'norm', 'discriminant',
        'integral', 'principal', 'prime', 'real', 'complex', 'form', 'forms',
        'dimension', 'rank', 'image', 'identity', 'section', 'sections',
        'information', 'context', 'theory', 'object', 'canonical', 'connection',
        'arithmetic', 'prime ideal', 'ideal generated by', 'relation', 'compatible',
        'circle', 'projection', 'near', 'interval', 'derivation', 'pullback',
        'connected', 'distance']
    if ref != ANT:
        e['escapes'] += ['field', 'fields']
    ENTRIES.append(e)

add('number field', 'number-field', 'NumberField', '11R04',
    ['algebraic number field', 'number fields'], [],
    'field-extension algebraic-integer ring-of-integers-of-a-number-field', r"""
\begin{definition}
A \emph{number field} is a finite field extension \(K/\mathbb{Q}\). Its degree
\([K:\mathbb{Q}]\) is its dimension as a vector space over the rational numbers.
An embedding into \(\mathbb{C}\) can be chosen, but is not part of the abstract definition.
\end{definition}
\begin{example}
The rational field has degree one. The field \(\mathbb{Q}(\sqrt{2})\) consists
of the elements \(a+b\sqrt{2}\), with \(a,b\in\mathbb{Q}\), and has basis
\(1,\sqrt{2}\) and degree two. The polynomial \(X^2-2\) is irreducible over
\(\mathbb{Q}\), which establishes that degree.
\end{example}
\begin{proposition}
Every element of a number field is algebraic over \(\mathbb{Q}\).
\end{proposition}
\begin{proof}
If the degree is \(n\), the \(n+1\) elements \(1,a,\ldots,a^n\) are linearly
dependent over \(\mathbb{Q}\). A nonzero polynomial with rational coefficients
therefore vanishes at \(a\).
\end{proof}
Being algebraic is not enough to make an extension a number field: the field
of all algebraic numbers has infinite degree. Indeed, Eisenstein's criterion
applied at 2 makes \(X^m-2\) irreducible for every positive integer \(m\), so
that field contains subextensions of arbitrarily large finite degree.

Number-field arithmetic studies the [[ring-of-integers-of-a-number-field|ring of integers]]
inside \(K\), its ideals, and factorization of rational primes there.
""", ANT)

add('algebraic integer', 'algebraic-integer', 'AlgebraicInteger', '11R04',
    ['algebraic integers'], [], 'number-field integral-extension ring-of-integers-of-a-number-field', r"""
\begin{definition}
An element \(a\) of a field containing \(\mathbb{Q}\) is an \emph{algebraic
integer} if it satisfies a monic polynomial with coefficients in \(\mathbb{Z}\):
\[
a^n+c_{n-1}a^{n-1}+\cdots+c_0=0,\qquad c_i\in\mathbb{Z}.
\]
Thus it is integral over \(\mathbb{Z}\) in the sense of
[[integral-extension|integral extensions]]. The leading coefficient one is essential.
\end{definition}
\begin{example}
Both \(\sqrt{2}\) and \((1+\sqrt{5})/2\) are algebraic integers: they satisfy
\(X^2-2\) and \(X^2-X-1\), respectively. The rational number \(1/2\) is
algebraic, since \(2X-1\) vanishes there, but is not an algebraic integer.
\end{example}
\begin{proposition}
A rational number is an algebraic integer if and only if it is an integer.
\end{proposition}
\begin{proof}
Write it as \(a/b\), with coprime integers \(a,b\) and \(b>0\). Multiplying
a monic polynomial equation of degree \(n\) by \(b^n\) shows that \(b\)
divides \(a^n\). Coprimality forces \(b=1\). Conversely, an integer \(a\)
satisfies \(X-a=0\).
\end{proof}
The sums and products of algebraic integers are again algebraic integers,
by closure of integral elements under ring operations (see the reference).
Their inverses need not be: \(2\) is integral, but \(1/2\) is not.
Inside a [[number-field|number field]] these elements constitute its ring of integers.
""", ANT)

add('ring of integers of a number field', 'ring-of-integers-of-a-number-field',
    'RingOfIntegersOfANumberField', '11R04', ['number field ring of integers'], [],
    'number-field algebraic-integer integral-basis fractional-ideal-of-a-number-field', r"""
\begin{definition}
For a [[number-field|number field]] \(K\), its \emph{ring of integers} is
\[
\mathcal{O}_K=\{a\in K:a\text{ is an algebraic integer}\}.
\]
Equivalently, it is the integral closure of \(\mathbb{Z}\) in \(K\).
Closure of integral elements under addition, subtraction and multiplication
makes this a subring of \(K\).
\end{definition}
\begin{example}
We have \(\mathcal{O}_{\mathbb{Q}}=\mathbb{Z}\) and
\(\mathcal{O}_{\mathbb{Q}(i)}=\mathbb{Z}[i]\), the Gaussian integers.
For squarefree \(d\ne0,1\), the quadratic-field formula is
\(\mathcal{O}_{\mathbb{Q}(\sqrt d)}=\mathbb{Z}[(1+\sqrt d)/2]\) when
\(d\equiv1\pmod4\), and \(\mathbb{Z}[\sqrt d]\) otherwise.
In particular, \(\mathbb{Z}[\sqrt5]\) is strictly smaller than the full ring
of integers: it misses \((1+\sqrt5)/2\).
\end{example}
The quadratic formula and the following structural results are proved in
Chapters 2 and 3 of the reference. The additive group of \(\mathcal{O}_K\)
is free of rank \([K:\mathbb{Q}]\); its bases are called
[[integral-basis|integral bases]]. Its fraction field is \(K\).
Every nonzero ideal factors uniquely into nonzero prime ideals.

This last assertion concerns ideals: elements need not have unique
factorization into irreducibles. The [[ideal-class-group-of-a-number-field|ideal class group]]
measures whether all nonzero ideals are principal. Even when a single
algebraic integer generates \(K\) as a field, it need not generate
\(\mathcal{O}_K\) as a ring.
""", ANT)

add('integral basis', 'integral-basis', 'IntegralBasis', '11R04',
    ['integral basis of a number field'], ['power integral basis'],
    'number-field ring-of-integers-of-a-number-field discriminant-of-a-number-field', r"""
\begin{definition}
An \emph{integral basis} of a [[number-field|number field]] \(K\) of degree
\(n\) is a basis \(\omega_1,\ldots,\omega_n\) of the abelian group
\(\mathcal{O}_K\) over \(\mathbb{Z}\). Explicitly, every algebraic integer
in \(K\) has a unique expression \(\sum_i a_i\omega_i\) with
\(a_i\in\mathbb{Z}\).
\end{definition}
The integral-basis theorem guarantees existence; see Chapter 2 of the
reference. Such a basis is also a vector-space basis of \(K/\mathbb{Q}\).
The converse fails, even when every basis element is integral.
\begin{example}
For \(\mathbb{Q}(\sqrt5)\), an integral basis is
\(1,(1+\sqrt5)/2\). The pair \(1,\sqrt5\) is a rational vector-space basis
consisting of algebraic integers, but it cannot express \((1+\sqrt5)/2\)
with integer coefficients, so it is not an integral basis.
\end{example}
\begin{definition}
An integral basis of the special form \(1,\theta,\ldots,\theta^{n-1}\)
is a \emph{power integral basis}. It exists precisely when
\(\mathcal{O}_K=\mathbb{Z}[\theta]\) for some \(\theta\in\mathcal{O}_K\).
Not every number field has a power integral basis.
\end{definition}
Changing an integral basis uses an integer matrix with determinant \(\pm1\).
This is why the determinant defining the
[[discriminant-of-a-number-field|field discriminant]] is independent of that choice.
""", ANT)

add('discriminant of a number field', 'discriminant-of-a-number-field',
    'DiscriminantOfANumberField', '11R29', ['number field discriminant','field discriminant'], [],
    'integral-basis field-trace ramification-of-primes-in-a-number-field', r"""
\begin{definition}
Let \(\omega_1,\ldots,\omega_n\) be an [[integral-basis|integral basis]] of
a number field \(K\). Its \emph{field discriminant} is the nonzero integer
\[
D_K=\det\bigl(\operatorname{Tr}_{K/\mathbb{Q}}(\omega_i\omega_j)\bigr)_{1\le i,j\le n}.
\]
Here [[field-trace|field trace]] is the trace of the rational linear map
given by multiplication by the indicated element. Nondegeneracy of the
trace pairing for separable extensions gives nonvanishing.
\end{definition}
\begin{proposition}
This integer does not depend on the integral basis.
\end{proposition}
\begin{proof}
A basis change by \(A\in\operatorname{GL}_n(\mathbb{Z})\) replaces the trace
matrix \(T\) by \(A^{\mathsf{T}}TA\). Its determinant is multiplied by
\((\det A)^2=1\).
\end{proof}
\begin{example}
For \(K=\mathbb{Q}(\sqrt5)\), put \(\omega=(1+\sqrt5)/2\). Its conjugate
is \((1-\sqrt5)/2\), so \(\operatorname{Tr}(1)=2\),
\(\operatorname{Tr}(\omega)=1\), and \(\operatorname{Tr}(\omega^2)=3\).
Consequently \(D_K=2\cdot3-1\cdot1=5\).
Using \(1,\sqrt5\) instead gives 20, the discriminant of a nonintegral basis,
not the field discriminant.
\end{example}
A rational prime ramifies in \(K\) exactly when it divides \(D_K\).
This standard ramification criterion, proved in the reference, connects
the trace pairing to [[ramification-of-primes-in-a-number-field|prime ideal factorization]].
""", ANT)

add('fractional ideal of a number field', 'fractional-ideal-of-a-number-field',
    'FractionalIdealOfANumberField', '11R04', ['fractional ideals of a number field'], [],
    'ring-of-integers-of-a-number-field ideal-of-a-ring ideal-class-group-of-a-number-field', r"""
\begin{definition}
A \emph{nonzero fractional ideal} of a number field \(K\) is a nonzero
\(\mathcal{O}_K\)-submodule \(I\subseteq K\) such that
\(dI\subseteq\mathcal{O}_K\) for some nonzero \(d\in\mathcal{O}_K\).
Thus a common denominator turns it into an ordinary nonzero ideal.
An ordinary ideal is also called an integral ideal in this setting.
\end{definition}
Since \(\mathcal{O}_K\) is Noetherian, this agrees with the definition as a
nonzero finitely generated \(\mathcal{O}_K\)-submodule of \(K\).
The product \(IJ\) consists of finite sums of products \(ab\), with
\(a\in I\) and \(b\in J\).
\begin{example}
For \(K=\mathbb{Q}(i)\), the module \(\tfrac12\mathbb{Z}[i]\) is fractional
but not integral. Multiplying it by \(2\mathbb{Z}[i]\) gives \(\mathbb{Z}[i]\).
More generally, \(a\mathcal{O}_K\), for \(a\in K^\times\), is a principal
fractional ideal with inverse \(a^{-1}\mathcal{O}_K\).
\end{example}
Unique prime ideal factorization in \(\mathcal{O}_K\) implies that every
nonzero fractional ideal has an inverse
\[
I^{-1}=\{x\in K:xI\subseteq\mathcal{O}_K\},\qquad II^{-1}=\mathcal{O}_K.
\]
Consequently these ideals form an abelian group under multiplication.
The assertion uses the special properties of rings of integers; it is
not true for fractional ideals of every integral domain. Quotienting by
principal fractional ideals gives the [[ideal-class-group-of-a-number-field|ideal class group]].
""", ANT)

add('ideal class group of a number field', 'ideal-class-group-of-a-number-field',
    'IdealClassGroupOfANumberField', '11R29', ['ideal class group','ideal class groups'],
    ['class number of a number field'],
    'fractional-ideal-of-a-number-field ring-of-integers-of-a-number-field', r"""
\begin{definition}
Let \(I_K\) be the abelian group of nonzero fractional ideals of
\(\mathcal{O}_K\), and let \(P_K=\{a\mathcal{O}_K:a\in K^\times\}\).
The \emph{ideal class group} is \(\operatorname{Cl}(K)=I_K/P_K\).
Equivalently, \(I\) and \(J\) represent the same class if \(I=aJ\) for
some \(a\in K^\times\). Its order \(h_K\) is the \emph{class number}.
\end{definition}
The class group of a number field is finite (the class-number finiteness
theorem, proved in Chapter 4 of the reference). It is trivial precisely
when every ideal of \(\mathcal{O}_K\) is principal; for rings of integers,
this is also equivalent to unique factorization of elements.
\begin{example}
For \(\mathbb{Q}\), every fractional ideal is \(a\mathbb{Z}\) with
\(a\in\mathbb{Q}^\times\), so \(h_{\mathbb{Q}}=1\).
The Gaussian integers are Euclidean, hence principal, and also have trivial class group.
\end{example}
\begin{example}
In \(R=\mathbb{Z}[\sqrt{-5}]=\mathcal{O}_{\mathbb{Q}(\sqrt{-5})}\), the
ideal \(I=(2,1+\sqrt{-5})\) is not principal. Its quotient is the field of
two elements (send \(\sqrt{-5}\) to 1), so \([R:I]=2\).
If \(I=(a+b\sqrt{-5})\), this index would equal the absolute determinant
of multiplication by its generator, namely \(a^2+5b^2\).
No integers \(a,b\) make this equal to 2. Hence \(I\) represents a
nontrivial ideal class. This argument establishes nontriviality without
claiming to compute the whole class group.
\end{example}
""", ANT)

add('ramification of primes in a number field', 'ramification-of-primes-in-a-number-field',
    'RamificationOfPrimesInANumberField', '11R04', ['ramified rational prime'],
    ['ramification index of a prime ideal','residue degree of a prime ideal'],
    'number-field ring-of-integers-of-a-number-field discriminant-of-a-number-field', r"""
\begin{definition}
Let \(p\) be a positive rational prime and factor its ideal in a number field:
\[
p\mathcal{O}_K=\mathfrak{p}_1^{e_1}\cdots\mathfrak{p}_g^{e_g}.
\]
The \(\mathfrak{p}_i\) are distinct nonzero prime ideals. The exponent
\(e_i\) is the \emph{ramification index}, and
\(f_i=[\mathcal{O}_K/\mathfrak{p}_i:\mathbb{F}_p]\) is the \emph{residue degree}.
The prime \(p\) is ramified in \(K\) if some \(e_i>1\), and unramified otherwise.
\end{definition}
The fundamental degree relation is \(\sum_i e_i f_i=[K:\mathbb{Q}]\).
For a Galois extension all ramification indices agree, and all residue
degrees agree. These standard factorization results are proved in the reference.
\begin{example}
In \(\mathbb{Z}[i]\), \(2=-i(1+i)^2\), so
\((2)=(1+i)^2\) as ideals. Thus 2 ramifies, with \(e=2\) and \(f=1\).
By contrast, \((5)=(2+i)(2-i)\) is a product of distinct prime ideals,
each with residue field of order 5: it splits without ramification.
The ideal \((3)\) remains prime because \(X^2+1\) is irreducible over
\(\mathbb{F}_3\); here \(e=1\) and \(f=2\).
\end{example}
The notation \((a)\) means the ideal generated by \(a\), not merely that
element. Repeated prime ideal factors, rather than just splitting into
several factors, are what characterize ramification. Exactly the prime
divisors of the [[discriminant-of-a-number-field|field discriminant]] ramify;
for \(\mathbb{Q}(i)\) the discriminant is \(-4\).
""", ANT)

add('smooth manifold', 'smooth-manifold', 'SmoothManifold', '58A05',
    ['smooth manifolds'], ['smooth atlas','smooth structure','coordinate chart'],
    'smooth-map-between-manifolds tangent-space-of-a-smooth-manifold', r"""
\begin{definition}
A \emph{smooth manifold} of dimension \(n\) is a Hausdorff, second-countable
topological space \(M\) with a smooth structure. A \emph{coordinate chart}
is a homeomorphism \(x:U\to x(U)\subseteq\mathbb{R}^n\), where both sets
are open. A \emph{smooth atlas} is a collection of charts covering \(M\)
whose transition maps \(y\circ x^{-1}\) are infinitely differentiable on
their overlap domains. A \emph{smooth structure} is the maximal atlas
obtained by including every compatible chart.
\end{definition}
Here manifolds have no boundary, and their dimension is fixed. Hausdorff
means distinct points have disjoint neighborhoods; second countability
means the topology has a countable basis. Neither condition is to be
silently dropped. A smooth structure supplies more information than the topology alone.
\begin{example}
An open subset of \(\mathbb{R}^n\) has its usual smooth structure. The
circle \(x^2+y^2=1\) is a smooth one-dimensional manifold: on each open
semicircle, projection onto the appropriate coordinate gives a chart,
whose inverse uses one choice of sign of \(\sqrt{1-t^2}\).
On overlaps these coordinate changes are smooth.
\end{example}
The circle cannot be described by one global chart onto an open subset
of \(\mathbb{R}\): it is compact, whereas no nonempty open subset of
\(\mathbb{R}\) is compact. Local coordinates suffice for calculus.
[[smooth-map-between-manifolds|Smooth maps]] describe functions compatible
with these charts; [[tangent-space-of-a-smooth-manifold|tangent spaces]]
describe their first-order behavior.
""", DG)

add('smooth map between manifolds', 'smooth-map-between-manifolds',
    'SmoothMapBetweenManifolds', '57R35 58A05', ['smooth map','smooth maps'], [],
    'smooth-manifold tangent-space-of-a-smooth-manifold embedding', r"""
\begin{definition}
A map \(F:M\to N\) between smooth manifolds is \emph{smooth} if for each
\(p\in M\) there are charts \(x:U\to\mathbb{R}^m\) about \(p\) and
\(y:V\to\mathbb{R}^n\) about \(F(p)\), with \(F(U)\subseteq V\), such that
\(y\circ F\circ x^{-1}\) is infinitely differentiable.
The same property then holds in any compatible charts, by the chain rule.
\end{definition}
A bijective smooth map whose inverse is also smooth is a diffeomorphism.
This is the appropriate equivalence of smooth manifolds.
\begin{example}
The map \(t\mapsto(\cos t,\sin t)\) from \(\mathbb{R}\) to the circle is
smooth. The map \(t\mapsto t^3\) is a smooth bijection of \(\mathbb{R}\)
but is not a diffeomorphism: its inverse has no derivative at zero.
Thus bijectivity and smoothness alone do not suffice.
\end{example}
\begin{proposition}
The composite of smooth maps is smooth.
\end{proposition}
\begin{proof}
Choose charts near a point and its two successive images, shrinking the
source neighborhoods as needed. In coordinates the composite is the
composite of two smooth functions between Euclidean open sets, hence is
smooth by the chain rule.
\end{proof}
The derivative at \(p\), written \(dF_p:T_pM\to T_{F(p)}N\), is a linear
map between [[tangent-space-of-a-smooth-manifold|tangent spaces]]. Its matrix
in coordinate bases is the Jacobian of the coordinate expression of \(F\).
The chain rule is intrinsically \(d(G\circ F)_p=dG_{F(p)}\circ dF_p\).
""", DG)

add('tangent space of a smooth manifold', 'tangent-space-of-a-smooth-manifold',
    'TangentSpaceOfASmoothManifold', '58A05', ['tangent space','tangent spaces'], [],
    'smooth-manifold smooth-map-between-manifolds cotangent-space-of-a-smooth-manifold smooth-vector-field', r"""
\begin{definition}
Let \(p\) lie in an \(n\)-dimensional smooth manifold \(M\). Consider smooth
curves \(c\), defined on an interval about zero, with \(c(0)=p\). Two curves
represent the same \emph{tangent vector} if
\((x\circ c)'(0)=(x\circ d)'(0)\) in one chart \(x\) about \(p\).
The chain rule makes this independent of the chart. Their equivalence
classes form the \emph{tangent space} \(T_pM\).
\end{definition}
The velocity map \([c]\mapsto(x\circ c)'(0)\) identifies this set with
\(\mathbb{R}^n\) and gives it a vector-space structure. Chart changes
act by invertible linear Jacobians, so addition and scalar multiplication
are independent of the chart. In coordinates its basis is denoted
\(\partial/\partial x^1|_p,\ldots,\partial/\partial x^n|_p\).

A tangent vector acts on a smooth real function by
\(v(f)=(f\circ c)'(0)\). It satisfies
\(v(fh)=f(p)v(h)+h(p)v(f)\); this gives the equivalent derivation description.
\begin{example}
For the unit sphere \(S^2\subseteq\mathbb{R}^3\),
\(T_pS^2=\{v:p\cdot v=0\}\). Differentiating \(c(t)\cdot c(t)=1\)
gives this condition. Conversely, for \(v\perp p\), the curve
\((p+tv)/\|p+tv\|\) has initial velocity \(v\).
\end{example}
For a smooth map \(F\), define \(dF_p([c])=[F\circ c]\). Its coordinate
description is multiplication by the Jacobian, so it is well-defined and
linear. Tangent spaces at different points are distinct vector spaces;
there is generally no preferred identification between them.
""", DG)

add('cotangent space of a smooth manifold', 'cotangent-space-of-a-smooth-manifold',
    'CotangentSpaceOfASmoothManifold', '58A05', ['cotangent space','cotangent spaces'], [],
    'tangent-space-of-a-smooth-manifold differential-form riemannian-metric hamilton-equations', r"""
\begin{definition}
The \emph{cotangent space} at \(p\in M\) is the real dual vector space
\(T_p^*M=\operatorname{Hom}_{\mathbb{R}}(T_pM,\mathbb{R})\).
Its elements, called covectors, are linear functionals on tangent vectors.
For a smooth function \(f:M\to\mathbb{R}\), its differential at \(p\) is
the covector \(df_p(v)=v(f)\).
\end{definition}
In local coordinates \(x^1,\ldots,x^n\), the covectors \(dx^i|_p\) are
dual to \(\partial/\partial x^j|_p\): their pairing is \(\delta^i_j\).
Thus \(df_p=\sum_i (\partial f/\partial x^i)(p) dx^i|_p\).
\begin{example}
On \(\mathbb{R}^2\), if \(f(x,y)=x^2+y^2\), then
\(df_{(a,b)}=2a dx+2b dy\), and it sends a velocity \((u,v)\) to
\(2au+2bv\). A covector records a directional rate of change, rather
than being a velocity itself.
\end{example}
A smooth map \(F:M\to N\) pulls covectors back by the dual derivative:
\((dF_p)^*(\eta)=\eta\circ dF_p\). Consequently
\(d(h\circ F)_p=(dF_p)^*(dh_{F(p)})\).

The disjoint union \(T^*M=\coprod_{p\in M}T_p^*M\), with the smooth local
coordinates induced by charts and covector coefficients, is the cotangent
bundle. Smooth sections of it are [[differential-form|differential one-forms]].
Identifying a covector with a vector requires extra structure, such as a
[[riemannian-metric|Riemannian metric]]; there is no such preferred
identification on an arbitrary smooth manifold.
""", DG)

add('smooth vector field', 'smooth-vector-field', 'SmoothVectorField', '57R25 58A05',
    ['smooth vector fields'], ['integral curve of a vector field'],
    'smooth-manifold tangent-space-of-a-smooth-manifold gradient', r"""
\begin{definition}
A \emph{smooth vector field} on \(M\) assigns \(X_p\in T_pM\) to every
\(p\in M\), with smooth coordinate coefficients:
\[
X=\sum_{i=1}^n X^i\frac{\partial}{\partial x^i}.
\]
Smoothness is independent of coordinates, since transition Jacobians are
smooth. Equivalently it is a smooth section of the tangent bundle
\(TM=\coprod_{p\in M}T_pM\), whose charts use position and velocity coordinates.
\end{definition}
It acts on smooth functions by \((Xf)(p)=X_p(f)\) and satisfies
\(X(fh)=fX(h)+hX(f)\). Thus a vector field differentiates functions
in a direction that can vary from point to point.
\begin{definition}
An \emph{integral curve} of \(X\) is a smooth curve \(c:I\to M\) with
\(c'(t)=X_{c(t)}\). In coordinates this is the ordinary differential
equation \(\dot x^i=X^i(x)\).
\end{definition}
\begin{example}
On \(\mathbb{R}^2\), take \(X=-y \partial/\partial x+x \partial/\partial y\).
The integral curve starting at \((a,b)\) is
\(c(t)=(a\cos t-b\sin t,a\sin t+b\cos t)\), as direct differentiation
verifies. Nonzero starting points travel along circles; the origin stays fixed.
\end{example}
Smoothness guarantees local existence and uniqueness of integral curves,
but not existence for all time. For \(X=x^2\partial/\partial x\), the
curve starting at 1 is \(x(t)=1/(1-t)\), which cannot extend through \(t=1\).
A [[gradient|gradient]] is an important vector field, but constructing it
from a function requires a metric.
""", DG)

add('differential form', 'differential-form', 'DifferentialForm', '58A10',
    ['differential forms','differential one-form'], [],
    'cotangent-space-of-a-smooth-manifold smooth-manifold smooth-map-between-manifolds', r"""
\begin{definition}
A smooth \emph{differential form} of degree \(k\) on \(M\) assigns to
each \(p\) an alternating multilinear map
\(\omega_p:(T_pM)^k\to\mathbb{R}\), with smooth coefficients in every chart.
Equivalently it is a smooth section of \(\Lambda^kT^*M\). A form of
degree zero is a smooth real function. Locally,
\[
\omega=\sum_{i_1<\cdots<i_k} a_{i_1\ldots i_k} dx^{i_1}\wedge\cdots\wedge dx^{i_k}.
\]
Here the wedge of coordinate covectors evaluates on \(k\) vectors as the
determinant of their coordinate components in those rows. In particular,
\((dx\wedge dy)(u,v)=u_xv_y-u_yv_x\).
\end{definition}
\begin{example}
On the plane, \(dx\wedge dy\) measures oriented area. Interchanging the
two vectors reverses its sign. The one-form \(x dy-y dx\) sends a
velocity \((u,v)\) at \((x,y)\) to \(xv-yu\).
\end{example}
The exterior derivative is defined in coordinates by
\(d\omega=\sum_I da_I\wedge dx^{i_1}\wedge\cdots\wedge dx^{i_k}\),
where \(da_I=\sum_j(\partial a_I/\partial x^j)dx^j\).
This definition is independent of charts and satisfies \(d^2=0\).
For example \(d(x dy-y dx)=2 dx\wedge dy\).

Forms pull back along smooth maps by applying the derivative to each
vector argument. Unlike a general vector field, a form therefore has a
pullback along every smooth map. No Riemannian metric is needed to define
forms, their pullbacks, or exterior differentiation.
""", ('John M. Lee', 'Introduction to Smooth Manifolds, Chapters 14-15 (Differential Forms)',
       'https://sites.math.washington.edu/~lee/Books/ISM/'))

add('Riemannian metric', 'riemannian-metric', 'RiemannianMetric', '53B20',
    ['Riemannian metrics'], ['Riemannian manifold'],
    'smooth-manifold tangent-space-of-a-smooth-manifold cotangent-space-of-a-smooth-manifold geodesic gradient', r"""
\begin{definition}
A \emph{Riemannian metric} on a smooth manifold \(M\) assigns a positive
definite symmetric bilinear form \(g_p\) to every tangent space \(T_pM\),
varying smoothly with \(p\). The pair \((M,g)\) is a \emph{Riemannian manifold}.
In coordinates, \(g=\sum_{i,j}g_{ij} dx^i\otimes dx^j\), where the matrix
\((g_{ij})\) is smooth, symmetric and positive definite.
\end{definition}
It gives tangent vectors lengths \(\|v\|_g=\sqrt{g_p(v,v)}\) and defines
the length of a piecewise smooth curve by
\[
L(c)=\int_a^b\sqrt{g_{c(t)}(c'(t),c'(t))} dt.
\]
On a connected manifold, the infimum of lengths of curves joining two
points defines their Riemannian distance. The metric tensor and this
distance function are related but different objects.
\begin{example}
Euclidean space has \(g=\sum_i dx^i\otimes dx^i\). Restricting the
Euclidean inner product to the tangent planes of the unit sphere gives
its round metric. On the half-plane \(y>0\), the tensor
\(g=(dx\otimes dx+dy\otimes dy)/y^2\) is another Riemannian metric.
\end{example}
The metric identifies a vector \(v\) with the covector \(g_p(v,\cdot)\).
Thus the gradient is characterized by \(g(\operatorname{grad}f,X)=df(X)\).
Every smooth manifold under our Hausdorff and second-countable convention
admits a Riemannian metric, constructed by combining local Euclidean
metrics with a smooth partition of unity. Such a metric is additional
data, not a unique choice supplied by the smooth structure.
""", DG)

add('geodesic', 'geodesic', 'Geodesic', '53C22 53B20',
    ['Riemannian geodesic','geodesics'], [],
    'riemannian-metric smooth-manifold tangent-space-of-a-smooth-manifold', r"""
This entry uses the Riemannian meaning of geodesic, with an affine parameter.
\begin{definition}
A smooth curve \(c:I\to M\) in a Riemannian manifold is a \emph{geodesic}
if its covariant acceleration for the Levi-Civita connection is zero.
Explicitly, its coordinate functions satisfy
\[
\ddot x^k+\sum_{i,j}\Gamma^k_{ij}(x)\dot x^i\dot x^j=0,
\]
where the Christoffel coefficients are determined by the metric:
\[
\Gamma^k_{ij}=\frac12\sum_\ell g^{k\ell}
(\partial_i g_{j\ell}+\partial_j g_{i\ell}-\partial_\ell g_{ij}).
\]
Here \((g^{ij})\) is the inverse matrix of \((g_{ij})\), and
\(\partial_i=\partial/\partial x^i\). This equation is coordinate independent.
\end{definition}
\begin{example}
For the Euclidean metric the coefficients are constant, so all
\(\Gamma^k_{ij}\) vanish. The equation becomes \(\ddot x^k=0\), giving
\(c(t)=p+tv\): straight lines with constant velocity, including constant curves.
On the unit sphere with its round metric, nonconstant geodesics are
great circles traversed at constant speed. For orthonormal vectors
\(u,v\), the curve \(u\cos t+v\sin t\) has ambient acceleration
\(-c(t)\), which is normal to the sphere, hence zero tangential acceleration.
\end{example}
Given an initial point and velocity there is a unique local geodesic,
by the existence and uniqueness theorem for smooth ordinary differential equations.
Geodesics have constant speed and sufficiently short segments minimize
length. They need not minimize globally: a long great-circle arc is
longer than the other arc joining its endpoints.

An arbitrary reparametrization need not satisfy the displayed equation;
affine changes \(t\mapsto at+b\) preserve it. The image of a geodesic and
an affinely parametrized geodesic should therefore be distinguished.
""", DG)

def prepare(c):
    names = dict(c.execute('SELECT slug,canonical_name FROM math_concepts'))
    names.update({e['slug']:e['canonical'] for e in ENTRIES})
    for e in ENTRIES:
        e['targets'] = re.findall(r'\[\[([^|]+)\|[^]]+\]\]', e['body'])
        e['body'] = re.sub(r'\[\[([^|]+)\|([^]]+)\]\]',
            lambda m: r'\PMlinkname{'+m[2]+'}{'+names[m[1]]+'}',e['body'])
        for slug in e['related']:
            assert slug in names, slug

def apply(path):
    with sqlite3.connect(path) as c:
        c.row_factory = sqlite3.Row
        c.execute('PRAGMA foreign_keys=ON')
        prepare(c)
        for e in ENTRIES:
            if not c.execute('SELECT 1 FROM math_concepts WHERE slug=?',(e['slug'],)).fetchone():
                for term in [e['title'],*e['synonyms']]:
                    conflicts = c.execute('''SELECT title FROM math_concepts WHERE lower(title)=lower(?)
                        UNION SELECT synonym_text FROM math_synonyms WHERE lower(synonym_text)=lower(?)
                        UNION SELECT defined_term FROM math_definitions WHERE lower(defined_term)=lower(?)''',
                        (term,term,term)).fetchall()
                    assert not conflicts,(term,[tuple(r) for r in conflicts])
                create_math_concept(c.cursor(),e['canonical'],e['slug'],e['title'],
                    datetime.now().strftime('%Y-%m-%d %H:%M:%S'),'CWoo',source(e),1,
                    e['classifications'],document_types(e),e['synonyms'],e['definitions'],[])
        for e in ENTRIES:
            for slug in set(e['related']+e['targets']):
                relate(c,e['slug'],slug)
                relate(c,slug,e['slug'])
        for e in ENTRIES:
            d=fetch_public_math_concept_detail(c.cursor(),e['slug'])
            assert d['cleaned_tex']==source(e) and d['owner']=='CWoo'
            assert set(d['types'])==set(document_types(e)),e['slug']
            assert {r['code'] for r in d['classifications']}==set(e['classifications'])
            pat=r'\\\(.*?\\\)|\\\[.*?\\\]'
            original=re.findall(pat,d['cleaned_tex'],re.S)
            rendered=re.findall(pat,d['display_tex'],re.S)
            assert original==rendered,(e['slug'],[(a,b) for a,b in zip(original,rendered) if a!=b])
            for target in e['targets']:
                assert target in links(d['display_tex']),(e['slug'],target)
            for term in [e['title'],*e['synonyms']]:
                assert e['slug'] in links(apply_math_autolinker(-1,term,c.cursor())),term
            assert 'Definition' in d['types'] and 'Example' in d['types']
            print('Verified',d['id'],e['slug'])
        assert c.execute('PRAGMA integrity_check').fetchone()[0]=='ok'
        assert not c.execute('PRAGMA foreign_key_check').fetchall()

if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--db',type=Path,default=SRC.parent/'portfolio.db')
    args=p.parse_args()
    if not args.db.is_file():raise FileNotFoundError(args.db)
    apply(args.db)
