"""Give simple groups a standalone entry and link the composition-series definition."""
import argparse
from datetime import datetime
from pathlib import Path
import re
import sqlite3
from add_group_centralizers_and_series import entry, SRC, source, document_types, create_math_concept, fetch_public_math_concept_detail, relate, links
from services.math.concept_render_service import render_tex_reusing_existing_diagrams

ENTRY = entry('simple group', 'simple-group', 'SimpleGroup', '20E32 20D05',
    ['simple groups'], [],
    'group composition-series-of-a-group normal-series-of-groups solvable-group perfect-group center-of-a-group', r"""
Simple groups are the possible indivisible quotient layers in a \PMlinkname{composition series}{CompositionSeriesOfAGroup}.
\begin{definition}
A \emph{simple group} is a nontrivial group \(G\) whose only normal subgroups are \(\{1\}\) and \(G\). Thus
\[
N\trianglelefteq G\quad\Longrightarrow\quad N=\{1\}\text{ or }N=G.
\]
The definition applies to both finite and infinite groups. The trivial group is excluded.
\end{definition}
\begin{remark}
Simplicity rules out proper nontrivial normal subgroups, not all proper nontrivial subgroups. Equivalently, every quotient of a simple group is either trivial or isomorphic to the original group.
\end{remark}
\begin{proposition}
An abelian group is simple if and only if it is cyclic of prime order.
\end{proposition}
\begin{proof}
In an abelian simple group, choose \(g\ne1\). Its nontrivial cyclic subgroup is normal, so \(G=\gen{g}\). If \(g\) has infinite order, \(\gen{g^2}\) is a proper nontrivial subgroup, a contradiction. If its finite order \(n\) is composite, choose a prime divisor \(p<n\); then \(\gen{g^p}\) is again proper and nontrivial. Hence \(n\) is prime. Conversely, by Lagrange's theorem a group of prime order has no proper nontrivial subgroup at all, so it is simple.
\end{proof}
\begin{example}
The additive groups \(\mathbb{Z}/2\mathbb{Z}\), \(\mathbb{Z}/3\mathbb{Z}\), and \(\mathbb{Z}/5\mathbb{Z}\) are simple. The groups \(\mathbb{Z}\) and \(\mathbb{Z}/4\mathbb{Z}\) are not: the subgroups of even elements are proper, nontrivial, and normal.
\end{example}
\begin{example}
Let \(A_n\) be the alternating group of even permutations on \(n\) letters. The group \(A_5\), of order \(60\), is a nonabelian simple group. It still has proper nontrivial subgroups, such as \(\gen{(123)}\); these are not normal. In contrast, \(S_3\) is not simple, since its subgroup \(A_3\) is proper, nontrivial, and normal. Nor is \(A_4\) simple: its identity and the three double transpositions form a normal subgroup of order four.
\end{example}
\begin{proposition}
A nontrivial group \(G\) is simple if and only if every homomorphism from \(G\) to any group is either injective or trivial.
\end{proposition}
\begin{proof}
The kernel of a homomorphism is normal. For simple \(G\), a trivial kernel gives injectivity, whereas kernel \(G\) gives the trivial homomorphism. Conversely, for any normal subgroup \(N\), apply the assumed property to the quotient homomorphism \(G\to G/N\). Its kernel \(N\) must be trivial or all of \(G\).
\end{proof}
\begin{proposition}
Every nonabelian simple group has trivial center and is perfect.
\end{proposition}
\begin{proof}
The center is normal; if it were the whole group, the group would be abelian. Hence it is trivial. The subgroup \([G,G]\) generated by the commutators \(xyx^{-1}y^{-1}\) is normal, because conjugation takes commutators to commutators. It is nontrivial in a nonabelian group, so simplicity gives \([G,G]=G\), the definition of a perfect group.
\end{proof}
\section*{Notable results and further reading}
The following results are cited here; their full proofs are not supplied in this entry.
\begin{itemize}
\item The alternating group \(A_n\) is simple for every \(n\ge5\) (Milne, Theorem 4.33).
\item Jordan--Hölder: composition series of a finite group have the same simple factors, with multiplicities, up to isomorphism and reordering (Milne, Theorem 6.2).
\item Feit--Thompson: every finite group of odd order is solvable. Consequently every finite nonabelian simple group has even order (Milne, Theorem 6.4). Indeed, its commutator subgroup equals itself, so its derived series never reaches the identity.
\item The classification of finite simple groups lists cyclic groups of prime order, alternating groups of degree at least five, finite simple groups of Lie type, and 26 sporadic groups (Milne, Chapter 3, the Hölder program).
\end{itemize}
Composition factors alone do not determine a group: the cyclic group of order four and the Klein four group both have two factors of order two, but are not isomorphic.
""")
ENTRY['escapes'].append('injective')
ENTRY['reference']=('J. S. Milne','Group Theory, Chapters 3, 4 and 6 (v4.01)', 'https://www.jmilne.org/math/CourseNotes/GT.pdf')
OLD='A group is simple if it is nontrivial and its only normal subgroups are itself and the trivial subgroup. '
OLD_FACTOR='is a nontrivial simple group. '
NEW_FACTOR=r'is a \PMlinkname{simple group}{SimpleGroup}. '

def apply(path):
    with sqlite3.connect(path) as c:
        c.row_factory=sqlite3.Row
        c.execute('PRAGMA foreign_keys=ON')
        e=ENTRY
        now=datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        if not c.execute('SELECT 1 FROM math_concepts WHERE slug=?',(e['slug'],)).fetchone():
            for term in [e['title'],*e['synonyms']]:
                assert not c.execute('''SELECT title FROM math_concepts WHERE lower(title)=lower(?)
                    UNION SELECT synonym_text FROM math_synonyms WHERE lower(synonym_text)=lower(?)
                    UNION SELECT defined_term FROM math_definitions WHERE lower(defined_term)=lower(?)''',(term,term,term)).fetchone(),term
            create_math_concept(c.cursor(),e['canonical'],e['slug'],e['title'],now,'CWoo',source(e),1,
                e['classifications'],document_types(e),e['synonyms'],e['definitions'],[])
        d=fetch_public_math_concept_detail(c.cursor(),'composition-series-of-a-group')
        tex=d['cleaned_tex']
        if OLD in tex:
            assert OLD_FACTOR in tex
            tex=tex.replace(OLD,'').replace(OLD_FACTOR,NEW_FACTOR)
            rendered=render_tex_reusing_existing_diagrams(d['id'],tex,c.cursor())
            c.execute('UPDATE math_concepts SET cleaned_tex=?,rendered_tex=?,updated_at=? WHERE id=?',
                (tex,rendered,now,d['id']))
        assert OLD not in tex and NEW_FACTOR in tex
        for target in e['related']: relate(c,e['slug'],target)
        relate(c,'composition-series-of-a-group',e['slug'])
        for slug in [e['slug'],'composition-series-of-a-group']:
            d=fetch_public_math_concept_detail(c.cursor(),slug)
            assert d['owner']=='CWoo'
            pattern=r'\\\(.*?\\\)|\\\[.*?\\\]'
            assert re.findall(pattern,d['cleaned_tex'],re.S)==re.findall(pattern,d['display_tex'],re.S),slug
            assert ('composition-series-of-a-group' if slug==e['slug'] else e['slug']) in links(d['display_tex'])
            print('Verified',d['id'],slug)
        d=fetch_public_math_concept_detail(c.cursor(),e['slug'])
        assert d['cleaned_tex']==source(e)
        assert set(d['types'])==set(document_types(e))
        assert {r['code'] for r in d['classifications']}==set(e['classifications'])
        assert d['display_tex'].count('class="math-env math-env-proof"')==3
        assert c.execute('PRAGMA integrity_check').fetchone()[0]=='ok'
        assert not c.execute('PRAGMA foreign_key_check').fetchall()

if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--db',type=Path,default=SRC.parent/'portfolio.db')
    args=p.parse_args()
    if not args.db.is_file(): raise FileNotFoundError(args.db)
    apply(args.db)
